/*
 * GDMatrix
 *  
 * Copyright (C) 2020, Ajuntament de Sant Feliu de Llobregat
 *  
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 *  
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *    
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *    
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *    
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/ 
 * and 
 * https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.doc.uploader;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author real
 */
public class ImageViewer extends javax.swing.JDialog
{
  /**
   * Creates new form ImageViewer
   */
  public ImageViewer(java.awt.Frame parent)
  {
    super(parent, true);
    initComponents();
  }
  
  public void showImage(Image image)
  {
    imageLabel.setIcon(new ImageIcon(image));
    imageLabel.setText(null);
  }
  
  public void processImage(final ImageProcessor processor)
  {
    Thread thread = new Thread()
    {
      @Override
      public void run()
      {
        try
        {
          BufferedImage image = processor.processImage();
          publishImage(image);
        }
        catch (IOException ex)
        {       
          publishError(ex);
        }
      }
    };
    thread.start();
  }

  private void publishImage(final BufferedImage image)
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      public void run()
      {
        showImage(image);
      }
    });
  }

  private void publishError(final Exception ex)
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      public void run()
      {
        imageLabel.setText(ex.toString());
      }
    });
  }  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    southPanel = new javax.swing.JPanel();
    closeButton = new javax.swing.JButton();
    scrollPane = new javax.swing.JScrollPane();
    imageLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Image viewer");

    closeButton.setText("Close");
    closeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closeButtonActionPerformed(evt);
      }
    });
    southPanel.add(closeButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

    imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imageLabel.setText("Loading...");
    imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    scrollPane.setViewportView(imageLabel);
    imageLabel.getAccessibleContext().setAccessibleName("image");

    getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
  {//GEN-HEADEREND:event_closeButtonActionPerformed
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel imageLabel;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JPanel southPanel;
  // End of variables declaration//GEN-END:variables
}
