/*
 * GDMatrix
 *  
 * Copyright (C) 2020, Ajuntament de Sant Feliu de Llobregat
 *  
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 *  
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *    
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *    
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *    
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/ 
 * and 
 * https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.matrix.client.ui.doc;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import org.matrix.dic.Property;
import org.santfeliu.matrix.client.Command;
import org.santfeliu.matrix.client.ui.util.SelectItem;
import org.santfeliu.util.TextUtils;

/**
 *
 * @author blanquepa
 */
public class DocumentFrame extends JFrame
{
  public static final int NO = 0;
  public static final int YES = 1;  

  private int response = -1;  
  private File exploreDir;
  private File file;
  private final Object lock = new Object();
  private Command command;

  /**
   * Creates new form DocumentFrame
   */
  public DocumentFrame(Command command)
  {
    this.command = command;
    initComponents();
    try
    {
      setIconImage(ImageIO.read(getClass().getResource("resources/document.png")));
    }
    catch (Exception ex)
    {      
    }
  }

  public void showFrame()
  {
    addWindowListener(new WindowAdapter()
    {
      @Override
      public void windowActivated(WindowEvent e)
      {
        setAlwaysOnTop(false);
      }
    });
    setLocationRelativeTo(null);
    setVisible(true);
    setAlwaysOnTop(true);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    docIdLabel = new javax.swing.JLabel();
    docIdTextField = new javax.swing.JTextField();
    versionLabel = new javax.swing.JLabel();
    versionTextField = new javax.swing.JTextField();
    fileLabel1 = new javax.swing.JLabel();
    filenameField = new javax.swing.JTextField();
    exploreButton = new javax.swing.JButton();
    titleLabel = new javax.swing.JLabel();
    typeLabel = new javax.swing.JLabel();
    typeComboBox = new javax.swing.JComboBox();
    languageLabel = new javax.swing.JLabel();
    languageComboBox = new javax.swing.JComboBox();
    stateLabel = new javax.swing.JLabel();
    stateComboBox = new javax.swing.JComboBox();
    lockedByTextField = new javax.swing.JTextField();
    lockedByLabel = new javax.swing.JLabel();
    propertiesLabel = new javax.swing.JLabel();
    propertiesScrollPane = new javax.swing.JScrollPane();
    propertiesTable = new javax.swing.JTable();
    addPropertyButton = new javax.swing.JButton();
    removePropertyButton = new javax.swing.JButton();
    lockUnlockButton = new javax.swing.JToggleButton();
    southPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    titleScrollPane = new javax.swing.JScrollPane();
    titleTextArea = new javax.swing.JTextArea();
    capturePanel = new javax.swing.JPanel();
    captureDateLabel = new javax.swing.JLabel();
    captureDateTextField = new javax.swing.JTextField();
    captureUserLabel = new javax.swing.JLabel();
    captureUserTextField = new javax.swing.JTextField();
    changePanel = new javax.swing.JPanel();
    changeDateLabel = new javax.swing.JLabel();
    changeDateTextField = new javax.swing.JTextField();
    changeUserLabel = new javax.swing.JLabel();
    changeUserTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/santfeliu/matrix/client/ui/doc/DocumentFrameBundle"); // NOI18N
    setTitle(bundle.getString("DocumentFrame.title")); // NOI18N
    setBounds(new java.awt.Rectangle(0, 0, 0, 0));
    setPreferredSize(new java.awt.Dimension(500, 500));
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        formWindowClosing(evt);
      }
    });
    getContentPane().setLayout(new java.awt.GridBagLayout());

    docIdLabel.setText(bundle.getString("DocumentFrame.docIdLabel.text")); // NOI18N
    docIdLabel.setMinimumSize(new java.awt.Dimension(80, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(docIdLabel, gridBagConstraints);

    docIdTextField.setEditable(false);
    docIdTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    docIdTextField.setText(bundle.getString("DocumentFrame.docIdTextField.text")); // NOI18N
    docIdTextField.setBorder(null);
    docIdTextField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        docIdTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(docIdTextField, gridBagConstraints);

    versionLabel.setText(bundle.getString("DocumentFrame.versionLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(versionLabel, gridBagConstraints);

    versionTextField.setEditable(false);
    versionTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    versionTextField.setText(bundle.getString("DocumentFrame.versionTextField.text")); // NOI18N
    versionTextField.setBorder(null);
    versionTextField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        versionTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(versionTextField, gridBagConstraints);

    fileLabel1.setText(bundle.getString("DocumentFrame.fileLabel1.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(fileLabel1, gridBagConstraints);

    filenameField.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        filenameFieldMouseClicked(evt);
      }
    });
    filenameField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        filenameFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(filenameField, gridBagConstraints);

    exploreButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    exploreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/explore.png"))); // NOI18N
    exploreButton.setText(bundle.getString("DocumentFrame.exploreButton.text")); // NOI18N
    exploreButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    exploreButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        exploreButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(exploreButton, gridBagConstraints);
    exploreButton.getAccessibleContext().setAccessibleName(bundle.getString("DocumentFrame.exploreButton.AccessibleContext.accessibleName")); // NOI18N

    titleLabel.setText(bundle.getString("DocumentFrame.titleLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(titleLabel, gridBagConstraints);

    typeLabel.setText(bundle.getString("DocumentFrame.typeLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(typeLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 433;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(typeComboBox, gridBagConstraints);

    languageLabel.setText(bundle.getString("DocumentFrame.languageLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(languageLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(languageComboBox, gridBagConstraints);

    stateLabel.setText(bundle.getString("DocumentFrame.stateLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(stateLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(stateComboBox, gridBagConstraints);

    lockedByTextField.setEditable(false);
    lockedByTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    lockedByTextField.setForeground(new java.awt.Color(255, 0, 0));
    lockedByTextField.setText(bundle.getString("DocumentFrame.lockedByTextField.text")); // NOI18N
    lockedByTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    lockedByTextField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        lockedByTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(lockedByTextField, gridBagConstraints);

    lockedByLabel.setText(bundle.getString("DocumentFrame.lockedByLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(lockedByLabel, gridBagConstraints);

    propertiesLabel.setText(bundle.getString("DocumentFrame.propertiesLabel.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(propertiesLabel, gridBagConstraints);

    propertiesTable.setModel(new PropertyTableModel(Collections.EMPTY_LIST));
    propertiesTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    propertiesTable.setDragEnabled(true);
    propertiesScrollPane.setViewportView(propertiesTable);
    if (propertiesTable.getColumnModel().getColumnCount() > 0)
    {
      propertiesTable.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("DocumentFrame.propertiesTable.columnModel.title0_1")); // NOI18N
      propertiesTable.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("DocumentFrame.propertiesTable.columnModel.title1_1")); // NOI18N
    }

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(propertiesScrollPane, gridBagConstraints);

    addPropertyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/insert.png"))); // NOI18N
    addPropertyButton.setText(bundle.getString("DocumentFrame.addPropertyButton.text")); // NOI18N
    addPropertyButton.setToolTipText(bundle.getString("DocumentFrame.addPropertyButton.toolTipText")); // NOI18N
    addPropertyButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    addPropertyButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        addPropertyButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(addPropertyButton, gridBagConstraints);

    removePropertyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/remove.png"))); // NOI18N
    removePropertyButton.setText(bundle.getString("DocumentFrame.removePropertyButton.text")); // NOI18N
    removePropertyButton.setToolTipText(bundle.getString("DocumentFrame.removePropertyButton.toolTipText")); // NOI18N
    removePropertyButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    removePropertyButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        removePropertyButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(removePropertyButton, gridBagConstraints);

    lockUnlockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/lock-open.png"))); // NOI18N
    lockUnlockButton.setText(bundle.getString("DocumentFrame.lockUnlockButton.text")); // NOI18N
    lockUnlockButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    lockUnlockButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        lockUnlockButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(lockUnlockButton, gridBagConstraints);

    southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/ok.png"))); // NOI18N
    okButton.setText(bundle.getString("DocumentFrame.okButton.text")); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });
    southPanel.add(okButton);

    cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/cancel.png"))); // NOI18N
    cancelButton.setText(bundle.getString("DocumentFrame.cancelButton.text")); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });
    southPanel.add(cancelButton);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 16;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    getContentPane().add(southPanel, gridBagConstraints);

    titleScrollPane.setMinimumSize(new java.awt.Dimension(25, 60));

    titleTextArea.setColumns(20);
    titleTextArea.setFont(filenameField.getFont());
    titleTextArea.setLineWrap(true);
    titleTextArea.setRows(4);
    titleScrollPane.setViewportView(titleTextArea);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    getContentPane().add(titleScrollPane, gridBagConstraints);

    capturePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    captureDateLabel.setText(bundle.getString("DocumentFrame.captureDateLabel.text")); // NOI18N
    capturePanel.add(captureDateLabel);

    captureDateTextField.setEditable(false);
    captureDateTextField.setText(bundle.getString("DocumentFrame.captureDateTextField.text")); // NOI18N
    captureDateTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    capturePanel.add(captureDateTextField);

    captureUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    captureUserLabel.setText(bundle.getString("DocumentFrame.captureUserLabel.text")); // NOI18N
    capturePanel.add(captureUserLabel);

    captureUserTextField.setEditable(false);
    captureUserTextField.setText(bundle.getString("DocumentFrame.captureUserTextField.text")); // NOI18N
    captureUserTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    capturePanel.add(captureUserTextField);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(capturePanel, gridBagConstraints);

    changePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    changeDateLabel.setText(bundle.getString("DocumentFrame.changeDateLabel.text")); // NOI18N
    changePanel.add(changeDateLabel);

    changeDateTextField.setEditable(false);
    changeDateTextField.setText(bundle.getString("DocumentFrame.changeDateTextField.text")); // NOI18N
    changeDateTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    changePanel.add(changeDateTextField);

    changeUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    changeUserLabel.setText(bundle.getString("DocumentFrame.changeUserLabel.text")); // NOI18N
    changePanel.add(changeUserLabel);

    changeUserTextField.setEditable(false);
    changeUserTextField.setText(bundle.getString("DocumentFrame.changeUserTextField.text")); // NOI18N
    changeUserTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    changeUserTextField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        changeUserTextFieldActionPerformed(evt);
      }
    });
    changePanel.add(changeUserTextField);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 15;
    gridBagConstraints.gridwidth = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    getContentPane().add(changePanel, gridBagConstraints);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    ResourceBundle bundle = ResourceBundle.getBundle(
      "org/santfeliu/matrix/client/ui/doc/DocumentFrameBundle");
    String filename = filenameField.getText();
    if (filename == null || filename.length() == 0)
    {
      JOptionPane.showMessageDialog(this, 
        bundle.getString("DocumentFrame.filenameIsMandatory"), 
        "ERROR", JOptionPane.WARNING_MESSAGE);  
      return;
    }
    String title = titleTextArea.getText();
    if (title == null || title.length() == 0)
    {
      JOptionPane.showMessageDialog(this, 
        bundle.getString("DocumentFrame.titleIsMandatory"), 
        "ERROR", JOptionPane.WARNING_MESSAGE);  
      return;
    }
    SelectItem item = (SelectItem)typeComboBox.getSelectedItem();
    if (item.getId().length() == 0)
    {
      JOptionPane.showMessageDialog(this, 
        bundle.getString("DocumentFrame.typeIsMandatory"), 
        "ERROR", JOptionPane.WARNING_MESSAGE);
      return;
    }
    sendResponse(YES);
  }//GEN-LAST:event_okButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    sendResponse(NO);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void exploreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreButtonActionPerformed
    exploreDirectory();
  }//GEN-LAST:event_exploreButtonActionPerformed

  private void filenameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameFieldActionPerformed
    
  }//GEN-LAST:event_filenameFieldActionPerformed

  private void filenameFieldMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_filenameFieldMouseClicked
  {//GEN-HEADEREND:event_filenameFieldMouseClicked
    if (filenameField.getText() == null || filenameField.getText().length() == 0) exploreDirectory();
  }//GEN-LAST:event_filenameFieldMouseClicked

  private void changeUserTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changeUserTextFieldActionPerformed
  {//GEN-HEADEREND:event_changeUserTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_changeUserTextFieldActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    sendResponse(NO);
  }//GEN-LAST:event_formWindowClosing

  private void addPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropertyButtonActionPerformed
    int selectedRow = propertiesTable.getSelectedRow();
    PropertyTableModel tableModel = (PropertyTableModel)propertiesTable.getModel();
    tableModel.addRow(selectedRow, new Property());
    tableModel.fireTableRowsInserted(selectedRow, selectedRow);
    selectedRow = selectedRow > 0 ? selectedRow + 1 : tableModel.getRowCount() - 1;    
    propertiesTable.changeSelection(selectedRow, 0, false, false);
  }//GEN-LAST:event_addPropertyButtonActionPerformed

  private void removePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePropertyButtonActionPerformed
    int selectedRow = propertiesTable.getSelectedRow();
    if (selectedRow < 0)
      selectedRow = propertiesTable.getRowCount() - 1;
    if (selectedRow >= 0)  
    {
      PropertyTableModel tableModel = (PropertyTableModel)propertiesTable.getModel();
      tableModel.removeRow(selectedRow);
      tableModel.fireTableRowsDeleted(selectedRow, selectedRow);
    }
  }//GEN-LAST:event_removePropertyButtonActionPerformed

  private void lockUnlockButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lockUnlockButtonActionPerformed
  {//GEN-HEADEREND:event_lockUnlockButtonActionPerformed
    // TODO add your handling code here:
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/santfeliu/matrix/client/ui/doc/DocumentFrameBundle"); // NOI18N
    if (!lockUnlockButton.isSelected())
    {
      lockedByTextField.setText(null);
      lockUnlockButton.setText(bundle.getString("DocumentFrame.lockUnlockButton.text"));
      lockUnlockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/lock-open.png"))); // NOI18N      
      lockedByLabel.setText(bundle.getString("DocumentFrame.lockUnlockButton.text"));
    }
    else
    {
      lockedByTextField.setText((String)command.getProperties().get("userId"));
      lockUnlockButton.setText(bundle.getString("DocumentFrame.lockUnlockButton.text2"));      
      lockUnlockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/doc/resources/lock.png"))); // NOI18N      
      lockedByLabel.setText(bundle.getString("DocumentFrame.lockedByLabel.text"));      
    }
  }//GEN-LAST:event_lockUnlockButtonActionPerformed

  private void lockedByTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lockedByTextFieldActionPerformed
  {//GEN-HEADEREND:event_lockedByTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_lockedByTextFieldActionPerformed

  private void docIdTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_docIdTextFieldActionPerformed
  {//GEN-HEADEREND:event_docIdTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_docIdTextFieldActionPerformed

  private void versionTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_versionTextFieldActionPerformed
  {//GEN-HEADEREND:event_versionTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_versionTextFieldActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      Logger.getLogger(DocumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      Logger.getLogger(DocumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      Logger.getLogger(DocumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      Logger.getLogger(DocumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new DocumentFrame(null).showFrame();
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addPropertyButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel captureDateLabel;
  private javax.swing.JTextField captureDateTextField;
  private javax.swing.JPanel capturePanel;
  private javax.swing.JLabel captureUserLabel;
  private javax.swing.JTextField captureUserTextField;
  private javax.swing.JLabel changeDateLabel;
  private javax.swing.JTextField changeDateTextField;
  private javax.swing.JPanel changePanel;
  private javax.swing.JLabel changeUserLabel;
  private javax.swing.JTextField changeUserTextField;
  private javax.swing.JLabel docIdLabel;
  private javax.swing.JTextField docIdTextField;
  private javax.swing.JButton exploreButton;
  private javax.swing.JLabel fileLabel1;
  private javax.swing.JTextField filenameField;
  private javax.swing.JComboBox languageComboBox;
  private javax.swing.JLabel languageLabel;
  private javax.swing.JToggleButton lockUnlockButton;
  private javax.swing.JLabel lockedByLabel;
  private javax.swing.JTextField lockedByTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JLabel propertiesLabel;
  private javax.swing.JScrollPane propertiesScrollPane;
  private javax.swing.JTable propertiesTable;
  private javax.swing.JButton removePropertyButton;
  private javax.swing.JPanel southPanel;
  private javax.swing.JComboBox stateComboBox;
  private javax.swing.JLabel stateLabel;
  private javax.swing.JLabel titleLabel;
  private javax.swing.JScrollPane titleScrollPane;
  private javax.swing.JTextArea titleTextArea;
  private javax.swing.JComboBox typeComboBox;
  private javax.swing.JLabel typeLabel;
  private javax.swing.JLabel versionLabel;
  private javax.swing.JTextField versionTextField;
  // End of variables declaration//GEN-END:variables
  
  public JTextField getDocIdTextField()
  {
    return docIdTextField;
  }
  
  public JTextField getVersionTextField()
  {
    return versionTextField;
  }  
  
  public JComboBox getLanguageComboBox() 
  {
    return languageComboBox;
  }

  public JTextArea getTitleTextArea() 
  {
    return titleTextArea;
  }

  public JComboBox getTypeComboBox() 
  {
    return typeComboBox;
  }

  public JComboBox getStateComboBox()
  {
    return stateComboBox;
  }

  public JTextField getCaptureDateTextField()
  {
    return captureDateTextField;
  }

  public JTextField getCaptureUserTextField()
  {
    return captureUserTextField;
  }

  public JTextField getChangeDateTextField()
  {
    return changeDateTextField;
  }

  public JTextField getChangeUserTextField()
  {
    return changeUserTextField;
  }

  public JTextField getLockedByTextField()
  {
    return lockedByTextField;
  }

  public JTable getPropertiesTable() {
    return propertiesTable;
  }

  public void setPropertiesTable(JTable propertiesTable) {
    this.propertiesTable = propertiesTable;
  }

  public JToggleButton getLockUnlockButton()
  {
    return lockUnlockButton;
  }

  public void setLockUnlockButton(JToggleButton lockUnlockButton)
  {
    this.lockUnlockButton = lockUnlockButton;
  }

  public File getFile()
  {
    return file;
  }
  
  public int waitForResponse() throws InterruptedException
  {
    while (response == -1 && isShowing())
    {
      synchronized (lock)
      {
        lock.wait();
      }
    }
    return response;
  }

  private void sendResponse(int response)
  {
    this.response = response;
    setVisible(false);
    dispose();
    synchronized (lock)
    {
      lock.notifyAll();
    }
  }  
  
  private void exploreDirectory()
  {
    JFileChooser dialog = new JFileChooser();
    dialog.setDialogTitle("File chooser");
    if (exploreDir != null)
      dialog.setCurrentDirectory(exploreDir);
    int result = dialog.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION)
    {
      file = dialog.getSelectedFile();
      exploreDir = file.getParentFile();
      filenameField.setText(file.getAbsolutePath());
      if (this.titleTextArea.getText() == null || this.titleTextArea.getText().length() == 0)
      {
        if (file.getName().contains("."))
        {
          String filename = file.getName();
          titleTextArea.setText(filename.substring(0, filename.lastIndexOf(".")));        
        }
      }
    }
  }

  public void setPropertyTableModel(List<Property> docProps) 
  {
    getPropertiesTable().setModel(new PropertyTableModel(docProps));
  }

  public class PropertyTableModel extends AbstractTableModel implements TableModel
  {
    ArrayList<Property> properties;
    
    public PropertyTableModel(List<Property> properties)
    {
      this.properties = new ArrayList();
      if (properties != null)
        this.properties.addAll(properties);
    }
    
    public int getRowCount() 
    {
      return properties.size();
    }

    public int getColumnCount() 
    {
      return 2;
    }

    @Override
    public String getColumnName(int columnIndex) 
    {
      java.util.ResourceBundle bundle = 
        java.util.ResourceBundle.getBundle("org/santfeliu/matrix/client/ui/doc/DocumentFrameBundle"); // NOI18N
      if (columnIndex == 0)
        return bundle.getString("DocumentFrame.propertiesTable.columnModel.title0_1");
      else
        return bundle.getString("DocumentFrame.propertiesTable.columnModel.title1_1");
    }

    @Override
    public Class<?> getColumnClass(int columnIndex) 
    {
      return String.class;
    }

    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex) 
    {
      return true;
    }

    public Object getValueAt(int rowIndex, int columnIndex) 
    {
      if (properties.size() > rowIndex)
      {
        Property property = properties.get(rowIndex);
        if (columnIndex == 0)
          return property.getName();
        else
        {
          if (property.getValue() != null && property.getValue().size() > 1)
            return property.getValue();
          else 
            return TextUtils.collectionToString(property.getValue());
        }
      }
      return null;
    }

    @Override
    public void setValueAt(Object aValue, int rowIndex, int columnIndex) 
    {
      if (properties.size() > rowIndex)
      {
        Property property = properties.get(rowIndex);
        if (property != null)
        {
          if (columnIndex == 0)
            property.setName(String.valueOf(aValue));
          else
          {
            property.getValue().clear();
            String value = (String)aValue;
            if (value.startsWith("[") && value.endsWith("]"))
            {
              value = value.substring(1);
              value = value.substring(0, value.length() - 1);
              property.getValue().addAll(TextUtils.stringToList(value, ","));
            }
            else
              property.getValue().add(value);
          }
        }
      }
    }
    
    public List<Property> getValues()
    {
      return properties;
    }

    public void addRow(int rowIndex, Property property)
    {
      if (rowIndex < 0)
        rowIndex = properties.size();
      else
        rowIndex++;
      properties.add(rowIndex, property);
      fireTableRowsInserted(rowIndex, rowIndex);
    }
    
    public void removeRow(int rowIndex)
    {
      properties.remove(rowIndex);
      fireTableRowsDeleted(rowIndex, rowIndex);
    }
  }
}
