/*
 * GDMatrix
 *  
 * Copyright (C) 2020, Ajuntament de Sant Feliu de Llobregat
 *  
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 *  
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *    
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *    
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *    
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/ 
 * and 
 * https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.matrix.client.ui.scanner;

import java.awt.event.ActionListener;

/**
 *
 * @author realor
 */
public class TabPanel extends javax.swing.JPanel
{
  ActionListener closeAction;
  /**
   * Creates new form TabPanel
   */
  public TabPanel(String title, ActionListener closeAction)
  {
    initComponents();    
    this.tabLabel.setText(title);
    this.closeAction = closeAction;
  }
  
  public String getTitle()
  {
    return this.tabLabel.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    tabLabel = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 2, 1));
    setOpaque(false);
    setLayout(new java.awt.BorderLayout());

    tabLabel.setText("tabLabel");
    tabLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));
    tabLabel.setFocusable(false);
    add(tabLabel, java.awt.BorderLayout.CENTER);

    closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/scanner/resources/images/close_tab.png"))); // NOI18N
    closeButton.setMnemonic('c');
    closeButton.setToolTipText("close");
    closeButton.setBorder(null);
    closeButton.setBorderPainted(false);
    closeButton.setContentAreaFilled(false);
    closeButton.setFocusPainted(false);
    closeButton.setFocusable(false);
    closeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    closeButton.setOpaque(false);
    closeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/scanner/resources/images/close_tab.png"))); // NOI18N
    closeButton.setRolloverEnabled(true);
    closeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/santfeliu/matrix/client/ui/scanner/resources/images/hover_close_tab.png"))); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closeButtonActionPerformed(evt);
      }
    });
    add(closeButton, java.awt.BorderLayout.LINE_END);
  }// </editor-fold>//GEN-END:initComponents

  private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
  {//GEN-HEADEREND:event_closeButtonActionPerformed
    closeAction.actionPerformed(evt);
  }//GEN-LAST:event_closeButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel tabLabel;
  // End of variables declaration//GEN-END:variables
}
