/*
 * GDMatrix
 *  
 * Copyright (C) 2020, Ajuntament de Sant Feliu de Llobregat
 *  
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 *  
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *    
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *    
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *    
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/ 
 * and 
 * https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.matrix.ide;

import javax.swing.JOptionPane;

/**
 *
 * @author realor
 */
public class RoleDialog extends javax.swing.JDialog
{
  boolean accept = false;

  /** Creates new form RoleDialog */
  public RoleDialog(java.awt.Frame parent)
  {
    super(parent, true);
    initComponents();
  }

  public void setRoleId(String roleId)
  {
    roleIdTextField.setText(roleId);
  }

  public String getRoleId()
  {
    return roleIdTextField.getText();
  }

  public void setRoleName(String name)
  {
    nameTextField.setText(name);
  }

  public String getRoleName()
  {
    return nameTextField.getText();
  }

  public void setComments(String comments)
  {
    commentsTextArea.setText(comments);
  }

  public String getComments()
  {
    return commentsTextArea.getText();
  }

  public boolean showDialog()
  {
    setVisible(true);
    return accept;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    centralPanel = new javax.swing.JPanel();
    roleIdLabel = new javax.swing.JLabel();
    roleIdTextField = new javax.swing.JTextField();
    nameLabel = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();
    commentsLabel = new javax.swing.JLabel();
    scrollPane = new javax.swing.JScrollPane();
    commentsTextArea = new javax.swing.JTextArea();
    southPanel = new javax.swing.JPanel();
    acceptButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Role properties");

    centralPanel.setLayout(new java.awt.GridBagLayout());

    roleIdLabel.setText("RoleId:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(roleIdLabel, gridBagConstraints);

    roleIdTextField.setFont(new java.awt.Font("Monospaced", 0, 12));
    roleIdTextField.setMinimumSize(new java.awt.Dimension(140, 22));
    roleIdTextField.setPreferredSize(new java.awt.Dimension(140, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(roleIdTextField, gridBagConstraints);

    nameLabel.setText("Name:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(nameLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 282;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(nameTextField, gridBagConstraints);

    commentsLabel.setText("Comments:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(commentsLabel, gridBagConstraints);

    scrollPane.setHorizontalScrollBar(null);

    commentsTextArea.setFont(nameTextField.getFont());
    commentsTextArea.setLineWrap(true);
    commentsTextArea.setRows(5);
    commentsTextArea.setWrapStyleWord(true);
    scrollPane.setViewportView(commentsTextArea);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 263;
    gridBagConstraints.ipady = 91;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    centralPanel.add(scrollPane, gridBagConstraints);

    getContentPane().add(centralPanel, java.awt.BorderLayout.CENTER);

    acceptButton.setText("Accept");
    acceptButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        acceptButtonActionPerformed(evt);
      }
    });
    southPanel.add(acceptButton);

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    southPanel.add(cancelButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acceptButtonActionPerformed
  {//GEN-HEADEREND:event_acceptButtonActionPerformed
    if (roleIdTextField.getText().trim().length() == 0)
    {
      JOptionPane.showMessageDialog(this, "RoleId is mandatory!",
       "WARNING", JOptionPane.WARNING_MESSAGE);
    }
    else
    {
      accept = true;
      setVisible(false);
      dispose();
    }
  }//GEN-LAST:event_acceptButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    accept = false;
    setVisible(false);
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {

      public void run()
      {
        RoleDialog dialog = new RoleDialog(new javax.swing.JFrame());
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {

          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton acceptButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel centralPanel;
  private javax.swing.JLabel commentsLabel;
  private javax.swing.JTextArea commentsTextArea;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JLabel roleIdLabel;
  private javax.swing.JTextField roleIdTextField;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JPanel southPanel;
  // End of variables declaration//GEN-END:variables
}
