/*
 * GDMatrix
 *  
 * Copyright (C) 2020, Ajuntament de Sant Feliu de Llobregat
 *  
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 *  
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *    
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *    
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *    
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 * http://www.gnu.org/licenses/ 
 * and 
 * https://www.gnu.org/licenses/lgpl.txt
 */
package org.santfeliu.matrix.ide;

import java.awt.Color;
import org.santfeliu.swing.text.JavaScriptEditorKit;
import org.santfeliu.swing.text.SymbolHighlighter;

/**
 *
 * @author realor
 */
public class ScriptEditor extends javax.swing.JDialog
{
  private boolean accept;

  /** Creates new form ScriptEditor */
  public ScriptEditor(java.awt.Frame parent)
  {
    super(parent, true);
    initComponents();
    textEditor.getTextPane().setEditorKitForContentType("text/javascript",
      new JavaScriptEditorKit());
    textEditor.getTextPane().setContentType("text/javascript");
    textEditor.getTextPane().setSelectionColor(new Color(198, 198, 198));
    textEditor.getTextPane().setFont(Options.getEditorFont());

    SymbolHighlighter symbolHighlighter =
      new SymbolHighlighter(textEditor.getTextPane(), "({[", ")}]");
  }

  public void setCode(String code)
  {
    textEditor.getTextPane().setText(code);
    textEditor.getTextPane().setCaretPosition(0);
  }

  public String getCode()
  {
    return textEditor.getTextPane().getText();
  }

  public boolean showDialog()
  {
    setVisible(true);
    return accept;
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    southPanel = new javax.swing.JPanel();
    acceptButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    centerPanel = new javax.swing.JPanel();
    label = new javax.swing.JLabel();
    textEditor = new org.santfeliu.swing.text.TextEditor();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Server Script");

    acceptButton.setText("Accept");
    acceptButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        acceptButtonActionPerformed(evt);
      }
    });
    southPanel.add(acceptButton);

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });
    southPanel.add(cancelButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

    centerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
    centerPanel.setLayout(new java.awt.BorderLayout());

    label.setText("Enter server javascript code:");
    centerPanel.add(label, java.awt.BorderLayout.NORTH);

    textEditor.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
    centerPanel.add(textEditor, java.awt.BorderLayout.CENTER);

    getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_acceptButtonActionPerformed
  {//GEN-HEADEREND:event_acceptButtonActionPerformed
    accept = true;
    setVisible(false);
    dispose();
  }//GEN-LAST:event_acceptButtonActionPerformed

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    accept = false;
    setVisible(false);
    dispose();
  }//GEN-LAST:event_cancelButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton acceptButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JPanel centerPanel;
  private javax.swing.JLabel label;
  private javax.swing.JPanel southPanel;
  private org.santfeliu.swing.text.TextEditor textEditor;
  // End of variables declaration//GEN-END:variables
}
