CREATE TABLE WFW_INSTANCE
(
  INSTANCEID NUMERIC NOT NULL,
  WORKFLOW CHARACTER VARYING(50) NOT NULL,
  EVENTCOUNT NUMERIC NOT NULL,
  PROCESSABLE CHARACTER(1),
  STARTDT CHARACTER(14),
  CONSTRAINT WFW_INSTANCE_PK PRIMARY KEY (INSTANCEID)
);

CREATE TABLE WFW_VARIABLE
(
  INSTANCEID NUMERIC NOT NULL,
  NAME CHARACTER VARYING(64) NOT NULL,
  TYPE CHARACTER(1) NOT NULL,
  VALUE CHARACTER VARYING(4000),
  CONSTRAINT WFW_VARIABLE_PK PRIMARY KEY (INSTANCEID,NAME),
  CONSTRAINT WFW_VARIABLE_INSTANCE_FK FOREIGN KEY (INSTANCEID)
    REFERENCES WFW_INSTANCE (INSTANCEID)
);

CREATE TABLE WFW_EVENT
(
  INSTANCEID NUMERIC NOT NULL,
  EVENTNUM NUMERIC NOT NULL,
  DISPATCHED CHARACTER(1),
  EVENTDATE CHARACTER(8) NOT NULL,
  EVENTHOUR CHARACTER(6) NOT NULL,
  ACTOR CHARACTER VARYING(50),
  CONSTRAINT WFW_EVENT_PK PRIMARY KEY (INSTANCEID,EVENTNUM),
  CONSTRAINT WFW_EVENT_INSTANCE_FK FOREIGN KEY (INSTANCEID)
    REFERENCES WFW_INSTANCE (INSTANCEID)
);

CREATE TABLE WFW_EVENTVAR
(
  INSTANCEID NUMERIC NOT NULL,
  EVENTNUM NUMERIC NOT NULL,
  NAME CHARACTER VARYING(64) NOT NULL,
  TYPE CHARACTER(1) NOT NULL,
  OLDVALUE CHARACTER VARYING(4000),
  NEWVALUE CHARACTER VARYING(4000),
  CONSTRAINT WFW_EVENTVAR_PK PRIMARY KEY (INSTANCEID,EVENTNUM,NAME),
  CONSTRAINT WFW_EVENTVAR_EVENT_FK FOREIGN KEY (INSTANCEID,EVENTNUM)
    REFERENCES WFW_EVENT (INSTANCEID,EVENTNUM)
);

CREATE TABLE WFW_TIMER
(
  INSTANCEID NUMERIC NOT NULL,
  DATETIME CHARACTER(14) NOT NULL,
  CONSTRAINT WFW_TIMER_PK PRIMARY KEY(INSTANCEID, DATETIME)
);

CREATE TABLE TABLESEQ 
(
  COUNTER CHARACTER VARYING(50), 
	"VALUE" NUMERIC,
  CONSTRAINT TABLESEQ_PK PRIMARY KEY ("COUNTER")
);

CREATE INDEX WFW_EVENTDATE_IDX ON WFW_EVENT (EVENTDATE);
CREATE INDEX WFW_VARIABLE_VALUE_IDX ON WFW_VARIABLE ("VALUE");
