CREATE TABLE SQL_CONNECTION 
(
  ALIAS CHARACTER VARYING(50) NOT NULL, 
  DRIVER CHARACTER VARYING(100) NOT NULL, 
  URL CHARACTER VARYING(100 BYTE) NOT NULL,
  CONSTRAINT SQL_CONNECTION_PK PRIMARY KEY (ALIAS) ENABLE
);