CREATE SYNONYM ORG_USUARI FOR <SCHEMA_GENESYS5>.ORG_USUARI;

-- global ------------------------------------------------------------
CREATE TABLE TABLESEQ
(
  COUNTER VARCHAR2(50) NOT NULL,
  "VALUE" NUMBER(10, 0) NOT NULL,
  CONSTRAINT TABLESEQ_PK PRIMARY KEY (COUNTER) ENABLE
);

-- sql module ----------------------------------------------------------

CREATE TABLE SQL_CONNECTION
(
  "ALIAS" VARCHAR2(30),
  DRIVER VARCHAR2(50) NOT NULL,
  "URL" VARCHAR2(50) NOT NULL,
  CONSTRAINT "SQL_CONNECTION_PK" PRIMARY KEY ("ALIAS") VALIDATE
);

-- security module -----------------------------------------------------

CREATE TABLE APL_ROL
(
  ROLCOD VARCHAR2(20) NOT NULL, -- CHANGE TO ROLEID
  ROLDESC VARCHAR2(100), -- CHANGE TO DESCRIPTION
  OBSERV VARCHAR2(400),
  ROLETYPEID VARCHAR2(50 BYTE), 
  CREATIONUSERID CHAR(20 BYTE), 
  CREATIONDT CHAR(14 BYTE), 
  CHANGEUSERID CHAR(20 BYTE), 
  CHANGEDT CHAR(14 BYTE), 
  CONSTRAINT PK_APL_ROL PRIMARY KEY (ROLCOD) ENABLE
);

CREATE TABLE APL_ROLROL
(
  ROLCOD VARCHAR2(20) NOT NULL, -- CHANGE TO ROLEID
  INROLCOD VARCHAR2(20) NOT NULL, -- CHANGE TO INROLEID
  CONSTRAINT PK_APL_ROLROL PRIMARY KEY (ROLCOD,INROLCOD) ENABLE,
  CONSTRAINT FK_APL_ROLROL_ROL FOREIGN KEY (ROLCOD)
    REFERENCES APL_ROL (ROLCOD) ENABLE,
  CONSTRAINT FK_APL_ROLROL_INROL FOREIGN KEY (INROLCOD)
    REFERENCES APL_ROL (ROLCOD) ENABLE
);

CREATE TABLE APL_ROLUSR
(
  USRCOD CHAR(20) NOT NULL, -- CHANGE TO USERID
  ROLCOD VARCHAR2(20) NOT NULL, -- CHANGE TO ROLEID
  COMMENTS VARCHAR2(1000),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8), 
  CONSTRAINT PK_APL_ROLUSR PRIMARY KEY (USRCOD,ROLCOD) ENABLE,
  CONSTRAINT FK_ROLUSR_ROL FOREIGN KEY (ROLCOD)
    REFERENCES APL_ROL (ROLCOD) ENABLE,
  CONSTRAINT FK_APLROLUSR_USR FOREIGN KEY (USRCOD)
    REFERENCES ORG_USUARI (USRCOD) ENABLE
);

-- dic module -----------------------------------------------------

CREATE TABLE DIC_TYPE
(
  TYPEID VARCHAR2(64) NOT NULL,
  SUPERTYPEID VARCHAR2(64),
  DESCRIPTION VARCHAR2(1000),
  "INSTANTIABLE" CHAR(1),
  RESTRICTED CHAR(1),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  MODIFYDT CHAR(14),
  MODIFYUSERID VARCHAR2(50),
  REMOVED CHAR(1),
  TYPEPATH VARCHAR2(2000),
  DETAIL VARCHAR2(2000),
  CONSTRAINT DIC_TYPE_PK PRIMARY KEY(TYPEID),
  CONSTRAINT DIC_TYPE_SUPERTYPE_FK FOREIGN KEY (SUPERTYPEID)
    REFERENCES DIC_TYPE (TYPEID) VALIDATE
);

CREATE TABLE DIC_PROPDEF
(
  TYPEID VARCHAR2(64) NOT NULL,
  PROPNAME VARCHAR2(64) NOT NULL,
  DESCRIPTION VARCHAR2(500) NOT NULL,
  PROPTYPE CHAR(1) NOT NULL,
  PROPSIZE NUMBER(10) NOT NULL,
  MINOCCURS NUMBER(10),
  MAXOCCURS NUMBER(10),
  DEFAULTVALUE VARCHAR2(1000),
  HIDDEN CHAR(1),
  READONLY CHAR(1),
  ENUMTYPEID VARCHAR2(64),
  CONSTRAINT DIC_PROPDEF_PK PRIMARY KEY(TYPEID, PROPNAME),
  CONSTRAINT DIC_PROPDEF_TYPE_FK FOREIGN KEY (TYPEID)
    REFERENCES DIC_TYPE (TYPEID) VALIDATE,
  CONSTRAINT DIC_PROPDEF_ENUMTYPE_FK FOREIGN KEY (ENUMTYPEID)
    REFERENCES DIC_ENUMTYPE (TYPEID) VALIDATE
);

CREATE TABLE DIC_ACL
(
  TYPEID VARCHAR2(64) NOT NULL,
  ROLEID VARCHAR2(50) NOT NULL,
  "ACTION" VARCHAR2(128) NOT NULL,
  CONSTRAINT DIC_ACL_PK PRIMARY KEY(TYPEID, ROLEID, "ACTION"),
  CONSTRAINT DIC_ACL_TYPE_FK FOREIGN KEY (TYPEID)
    REFERENCES DIC_TYPE (TYPEID) VALIDATE
);

CREATE TABLE DIC_ENUMTYPE
(
  TYPEID VARCHAR2(64) NOT NULL,
  SUPERTYPEID VARCHAR2(64),
  ENUMNAME VARCHAR2(200) NOT NULL,
  ITEMTYPE CHAR(1) NOT NULL,
  SORTED CHAR(1) NOT NULL,
  CREATIONDT CHAR(14) NOT NULL,
  CREATIONUSERID VARCHAR2(20) NOT NULL,
  CHANGEDT CHAR(14) NOT NULL,
  CHANGEUSERID VARCHAR2(20) NOT NULL,
  CONSTRAINT DIC_ENUMTYPE_PK PRIMARY KEY(TYPEID),
  CONSTRAINT DIC_ENUMTYPE_SUPERTYPE_FK FOREIGN KEY (SUPERTYPEID)
    REFERENCES DIC_ENUMTYPE (TYPEID) VALIDATE
)

CREATE TABLE DIC_ENUMTYPEITEM
(
  ENUMTYPEITEMID NUMBER(10) NOT NULL,
  TYPEID VARCHAR2(64) NOT NULL,
  VALUE VARCHAR2(200),
  IDX NUMBER(5) NOT NULL,
  LABEL VARCHAR2(1000),
  DESCRIPTION VARCHAR2(2000),
  CONSTRAINT DIC_ENUMTYPEITEM_PK PRIMARY KEY(ENUMTYPEITEMID),
  CONSTRAINT DIC_ENUMTYPEITEM_ENUMTYPE_FK FOREIGN KEY (TYPEID)
    REFERENCES DIC_ENUMTYPE (TYPEID) VALIDATE
)

CREATE INDEX DIC_TYPE_DESCRIPTION ON DIC_TYPE (DESCRIPTION);

-- survey module ---------------------------------------------------

CREATE TABLE SUR_SURVEY
(
  SURVID NUMBER(10),
  TEXT VARCHAR2(100) NOT NULL,
  "OPEN" CHAR(1) NOT NULL,
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  CONSTRAINT SUR_SURVEY_PK PRIMARY KEY (SURVID) VALIDATE
);

CREATE TABLE SUR_ANSWER
(
  SURVID NUMBER(10),
  ANSWERID NUMBER(2),
  TEXT VARCHAR2(100) NOT NULL,
  VOTES NUMBER(10) NOT NULL,
  CONSTRAINT SUR_ANSWER_PK PRIMARY KEY (SURVID, ANSWERID) VALIDATE,
  CONSTRAINT SUR_ANSWER_SUR_SURVEY_FK FOREIGN KEY (SURVID)
    REFERENCES SUR_SURVEY (SURVID) VALIDATE
);

-- news module -----------------------------------------------------

CREATE TABLE INF_SOURCE
(
  SOURCEID CHAR(2) NOT NULL,
  "NAME" VARCHAR2(100) NOT NULL,
  CONSTRAINT INF_SOURCE_PK PRIMARY KEY (SOURCEID) ENABLE
);

CREATE TABLE INF_NEW
(
  NEWID NUMBER(8, 0) NOT NULL,
  HEADLINE VARCHAR2(1000) NOT NULL,
  SUMMARY VARCHAR2(4000),
  TEXT BLOB,
  REGISTERDAY CHAR(8), -- CHANGE TO CREATIONDATE
  REGISTERHOUR CHAR(6),
  STARTDAY CHAR(8),
  STARTHOUR CHAR(6),
  ENDDAY CHAR(8),
  ENDHOUR CHAR(6),
  USERID CHAR(20),
  SOURCEID CHAR(2),
  DRAFT CHAR(1),
  KEYWORDS VARCHAR2(1000),
  CONSTRAINT INF_NEW_PK PRIMARY KEY (NEWID) ENABLE
);

CREATE TABLE INF_NEWSECTION
(
  NEWID NUMBER(8, 0) NOT NULL,
  SECTIONID VARCHAR2(50) NOT NULL,
  PRIORITY NUMBER(6, 0),
  READCOUNT NUMBER(6, 0),
  STICKY CHAR(1),
  CONSTRAINT INF_NEWSECTION_PK PRIMARY KEY (NEWID,SECTIONID) ENABLE,
  CONSTRAINT INF_NEWSECTION_NEW FOREIGN KEY (NEWID)
    REFERENCES INF_NEW(NEWID) ENABLE
);

CREATE TABLE INF_NEWDOC
(
  NEWID NUMBER(8, 0) NOT NULL,
  DOCID NUMBER(10, 0) NOT NULL,  
  NEWDOCTYPEID VARCHAR2(64) NOT NULL,
  CONSTRAINT INF_NEWDOC_PK PRIMARY KEY (NEWID,DOCID) ENABLE,
  CONSTRAINT INF_NEWDOC_NEW FOREIGN KEY (NEWID)
    REFERENCES INF_NEW (NEWID) ENABLE
);

-- doc module -----------------------------------------------------

CREATE TABLE DOM_DOCUMENT -- change to DOC_DOCUMENT
(
  DOCID NUMBER(10, 0) NOT NULL,
  VERSION NUMBER(8, 0) NOT NULL,
  DOCTYPEID VARCHAR2(64),
  "STATE" VARCHAR2(10),
  MODIFYDATE CHAR(14),
  CAPTUREDATE CHAR(14),
  CAPTUREUSER VARCHAR2(50), -- change to CAPTUREUSERID
  MODIFYUSER VARCHAR2(50), -- change to MODIFYUSERID
  TITLE VARCHAR2(512) NOT NULL,
  LOCKUSER VARCHAR2(50),
  CONTENTID CHAR(36),
  "LANGUAGE" CHAR(2),
  CREATIONDATE CHAR(8),
  LASTVERSION CHAR(1),
  CONSTRAINT PK_DOM_DOCUMENT PRIMARY KEY (DOCID,VERSION) VALIDATE
);

CREATE TABLE DOM_METADATA -- CHANGE to DOC_PROPERTY
(
  DOCID NUMBER(10, 0) NOT NULL,
  VERSION NUMBER(8, 0) NOT NULL,
  PROPNAME VARCHAR2(64) NOT NULL,
  INDX NUMBER(3, 0) NOT NULL,
  "VALUE" VARCHAR2(4000) NOT NULL,
  CONSTRAINT DOM_METADATA_PK PRIMARY KEY (DOCID,VERSION,PROPNAME,INDX) VALIDATE,
  CONSTRAINT DOM_METADATA_DOCUMENT_FK FOREIGN KEY (DOCID,VERSION)
    REFERENCES DOM_DOCUMENT(DOCID,VERSION) VALIDATE
);


CREATE TABLE DOM_DOCDOC -- Replaces old DOM_RELDOC
(
  DOCID NUMBER(10, 0) NOT NULL,
  RELTYPE VARCHAR2(32) NOT NULL,
  RELNAME VARCHAR2(255) NOT NULL,
  RELDOCID NUMBER(10, 0) NOT NULL,
  MODIFYDATE CHAR(14),
  MODIFYUSER VARCHAR2(50), -- CHANGE TO MODIFYUSERID
  CAPTUREDATE CHAR(14),
  CAPTUREUSER VARCHAR2(50), -- CHANGE TO CAPTUREUSERID
  CONSTRAINT PK_DOM_DOCDOC PRIMARY KEY (DOCID,RELTYPE,RELNAME) VALIDATE,
);

CREATE TABLE DOM_PERSON
(
  DOCPERSONID NUMBER(10) NOT NULL,
  DOCID NUMBER(10, 0) NOT NULL,
  VERSION NUMBER(8, 0) NOT NULL,
  PERSONID NUMBER(8, 0) NOT NULL,
  DOCPERSONTYPEID VARCHAR2(64) NOT NULL,
  COMMENTS VARCHAR2(200),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CONSTRAINT DOM_PERSON_PK PRIMARY KEY (DOCPERSONID) VALIDATE,
  CONSTRAINT DOM_PERSON_DOCUMENT_FK FOREIGN KEY (DOCID, VERSION)
    REFERENCES DOM_DOCUMENT (DOCID, VERSION) VALIDATE,
  CONSTRAINT DOM_PERSON_PERSON_FK FOREIGN KEY (PERSONID)
    REFERENCES <SCHEMA_GENESYS5>.NCL_PERSONA (PERSCOD) VALIDATE
);

CREATE TABLE DOM_MARKUP
(
  QUERY_ID VARCHAR2(36) NOT NULL,
  DOCUMENT CLOB,
  OFFSET NUMBER(20),
  LENGTH NUMBER(20)
);

CREATE TABLE CNT_CONTENT
(
  UUID CHAR(36) NOT NULL, -- CHANGE TO CONTENTID
  FILETYPE CHAR(1) NOT NULL,
  MIMETYPE VARCHAR2(200),
  CAPTUREUSER VARCHAR2(50),
  CAPTUREDATE VARCHAR2(14),
  "LANGUAGE" CHAR(2),
  CONTENTSIZE NUMBER(20, 0),
  CREATIONDATE VARCHAR2(14),
  PUID VARCHAR2(50),
  CONSTRAINT PK_CNT_CONTENT PRIMARY KEY(UUID) VALIDATE
);

CREATE TABLE CNT_INTERNAL
(
  UUID CHAR(36) NOT NULL, -- CHANGE TO CONTENTID
  "DATA" BLOB,
  FMT VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_INTERNAL PRIMARY KEY (UUID) VALIDATE,
  CONSTRAINT FK_CNT_INTERNAL_CNT_CONTENT FOREIGN KEY (UUID)
    REFERENCES CNT_CONTENT(UUID) VALIDATE
);

CREATE TABLE CNT_EXTERNAL
(
  UUID CHAR(36) NOT NULL, -- CHANGE TO CONTENTID
  URL VARCHAR2(1000) NOT NULL,
  FMT VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_CNT_EXTERNAL PRIMARY KEY (UUID) VALIDATE,
  CONSTRAINT FK_CNT_EXTERNAL_CNT_CONTENT FOREIGN KEY (UUID)
    REFERENCES CNT_CONTENT(UUID) VALIDATE
);

CREATE TABLE DOM_ACL
(
  DOCID NUMBER(10, 0) NOT NULL,
  VERSION NUMBER(8, 0) NOT NULL,
  ROLEID VARCHAR2(50) NOT NULL,
  "ACTION" VARCHAR2(128) NOT NULL,
  CONSTRAINT DOM_ACL_PK PRIMARY KEY(DOCID, VERSION, ROLEID, "ACTION") VALIDATE,
  CONSTRAINT DOM_ACL_DOCUMENT_FK FOREIGN KEY (DOCID, VERSION)
    REFERENCES DOM_DOCUMENT (DOCID, VERSION) VALIDATE
);

CREATE INDEX DOM_DOCUMENT_CONTENTID_IDX ON DOM_DOCUMENT (CONTENTID ASC);
CREATE INDEX DOM_METADATA_PROP_VALUE_IDX ON DOM_METADATA (PROPNAME, VALUE);

-- cases module ---------------------------------------------------

CREATE TABLE CAS_CASE
(
  CASEID NUMBER(10),
  INITDATE VARCHAR2(8) NOT NULL,
  INITHOUR VARCHAR2(6),
  ENDDATE VARCHAR2(8),
  ENDHOUR VARCHAR2(6),
  "TYPE" VARCHAR2(64) NOT NULL,
  "STATE" VARCHAR2(30),
  DESCRIPTION VARCHAR2(1000),
  "SOURCE" VARCHAR2(50),
  TITLE VARCHAR2(512),
  COMMENTS VARCHAR2(200),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CONSTRAINT CAS_CASE_PK PRIMARY KEY (CASEID) VALIDATE
);

CREATE TABLE CAS_CASEPROP
(
  CASEID NUMBER(10),
  PROPNAME VARCHAR2(100),
  PROPVALUE VARCHAR2(4000),
  INDX NUMBER(3) DEFAULT 0,
  CONSTRAINT CAS_CASEPROP_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE,
  CONSTRAINT CAS_CASEPROP_PK PRIMARY KEY (CASEID, PROPNAME, INDX) VALIDATE
);

CREATE TABLE CAS_PERSON
(
  CASEPERSONID NUMBER(10),
  CASEID NUMBER(10),
  PERSCOD VARCHAR2(32), -- CHANGE TO PERSONID
  CASEPERSONTYPEID VARCHAR2(64),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  COMMENTS VARCHAR2(200),  
  ADDRESSID VARCHAR2(32),
  CONTACTID VARCHAR2(32),
  CONTACTID2 VARCHAR2(32),
  CONTACTID3 VARCHAR2(32),
  REPPERSONID VARCHAR2(32),
  REPADDRESSID VARCHAR2(32),
  REPCONTACTID VARCHAR2(32),
  REPCONTACTID2 VARCHAR2(32),
  REPCONTACTID3 VARCHAR2(32),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CONSTRAINT CAS_PERSON_PK PRIMARY KEY (CASEPERSONID) VALIDATE,
  CONSTRAINT CAS_PERSON_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE
);

CREATE TABLE CAS_ADDRESS
(
  CASEID NUMBER(10),
  ADDRESSID VARCHAR2(32),
  RADIUS NUMBER(6),
  COMMENTS VARCHAR2(200),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  CASEADDRESSTYPEID VARCHAR2(64),
  CONSTRAINT CAS_ADDRESS_PK PRIMARY KEY (CASEID, ADDRESSID) VALIDATE,
  CONSTRAINT CAS_ADDRESS_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE
);

CREATE TABLE CAS_DEMAND
(
  DEMANDID NUMBER(10),
  DEMANDTYPE VARCHAR2(64) NOT NULL,
  COMMENTS VARCHAR2(200),
  CASEID NUMBER(10) NOT NULL,
  CONSTRAINT CAS_DEMAND_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE,
  CONSTRAINT CAS_DEMAND_PK PRIMARY KEY (DEMANDID) VALIDATE
);

CREATE TABLE CAS_PROBLEM
(
  PROBLEMID NUMBER(10),
  PROBLEMTYPE VARCHAR2(64) NOT NULL,
  PERSONID NUMBER(8),
  COMMENTS VARCHAR2(200),
  CASEID NUMBER(10) NOT NULL,
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  REASON VARCHAR2(20),
  PRIORITY NUMBER(3),
  CONSTRAINT CAS_PROBLEM_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE,
  CONSTRAINT CAS_PROBLEM_PK PRIMARY KEY (PROBLEMID) VALIDATE
);

CREATE TABLE CAS_INTERVENTION
(
  INTERVENTIONID NUMBER(10),
  CASEID NUMBER(10) NOT NULL ,
  "TYPE" VARCHAR2(64),
  INITDATE VARCHAR2(8),
  INITHOUR VARCHAR2(6),
  ENDDATE VARCHAR2(8),
  ENDHOUR VARCHAR2(6),
  PERSCOD VARCHAR2(32), -- CHANGE TO PERSONID
  USRNAME VARCHAR2(50),
  COMMENTS VARCHAR2(2000),
  CONSTRAINT CAS_INTERVENTION_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE,
  CONSTRAINT CAS_INTERVENTION_PK PRIMARY KEY (INTERVENTIONID) VALIDATE
);

CREATE TABLE CAS_INTERVENTIONPROP
(
  INTERVENTIONID NUMBER(10),
  PROPNAME VARCHAR2(100),
  PROPVALUE VARCHAR2(4000),
  CONSTRAINT CAS_INTERVENTIONPROP_FK FOREIGN KEY (INTERVENTIONID)
    REFERENCES CAS_INTERVENTION (INTERVENTIONID) VALIDATE,
  CONSTRAINT CAS_INTERVENTIONPROP_PK
    PRIMARY KEY (INTERVENTIONID, PROPNAME) VALIDATE
 );

CREATE TABLE CAS_INTPROB
(
  INTPROBID      NUMBER(10,0) NOT NULL ENABLE,
  INTERVENTIONID NUMBER(10,0),
  PROBLEMID      NUMBER(10,0),
  COMMENTS       VARCHAR2(200),
  CONSTRAINT CAS_INTPROB_PK PRIMARY KEY (INTPROBID) VALIDATE,
  CONSTRAINT CAS_INTPROB_CAS_INTERVENT_FK1 FOREIGN KEY (INTERVENTIONID) REFERENCES CAS_INTERVENTION (INTERVENTIONID) VALIDATE,
  CONSTRAINT CAS_INTPROB_CAS_PROBLEM_FK1 FOREIGN KEY (PROBLEMID) REFERENCES CAS_PROBLEM (PROBLEMID) VALIDATE
)

CREATE TABLE CAS_DOCUMENT
(
  CASEID NUMBER(10),
  DOCID NUMBER(10),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CASEDOCTYPEID VARCHAR2(64),
  COMMENTS VARCHAR2(200),
  VOLUME VARCHAR2(100)
  CONSTRAINT CAS_DOCUMENT_PK PRIMARY KEY (CASEID, DOCID) VALIDATE
);

CREATE TABLE CAS_ACL
(
  CASEID NUMBER(10) NOT NULL,
  ROLEID VARCHAR2(50) NOT NULL,
  "ACTION" VARCHAR2(128) NOT NULL,
  CONSTRAINT CAS_ACL_PK PRIMARY KEY(CASEID, ROLEID, "ACTION"),
  CONSTRAINT CAS_ACL_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE
);

CREATE TABLE CAS_EVENT
(
  CASEEVENTID NUMBER(10),
  CASEID NUMBER(10) NOT NULL,
  ESDEVCOD NUMBER(8) NOT NULL,
  CASEEVENTTYPEID VARCHAR2(64) NOT NULL,
  COMMENTS VARCHAR2(1000),
  CONSTRAINT CAS_EVENT_PK PRIMARY KEY(CASEEVENTID),
  CONSTRAINT CAS_EVENT_CASE_FK FOREIGN KEY (CASEID) REFERENCES CAS_CASE(CASEID) VALIDATE,
  CONSTRAINT CAS_EVENT_EVENT_FK FOREIGN KEY (ESDEVCOD) REFERENCES AGD_ESDEVENIMENT(ESDEVCOD) VALIDATE
);

CREATE TABLE CAS_EVENTPROP
(
  CASEEVENTID NUMBER(10),
  PROPNAME VARCHAR2(100),
  PROPVALUE VARCHAR2(4000),
  INDX NUMBER(3) DEFAULT 0,
  CONSTRAINT CAS_EVENTPROP_PK PRIMARY KEY (CASEEVENTID, PROPNAME, INDX) ENABLE,
  CONSTRAINT CAS_EVENTPROP_FK FOREIGN KEY (CASEEVENTID) REFERENCES CAS_EVENT(CASEEVENTID) ENABLE
);

CREATE TABLE CAS_CASECASE
(
  CASECASEID NUMBER(10),
  CASEID NUMBER(10),
  RELCASEID VARCHAR2(15),
  COMMENTS VARCHAR2(2000),
  CASECASETYPEID VARCHAR2(64),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8)
  CONSTRAINT CAS_CASECASE_CASE_FK FOREIGN KEY (CASEID)
    REFERENCES CAS_CASE (CASEID) VALIDATE,
  CONSTRAINT CAS_CASECASE_PK PRIMARY KEY (CASECASEID) VALIDATE
); 

CREATE TABLE CAS_CASECASEPROP
(
  CASECASEID NUMBER(10),
  PROPNAME VARCHAR2(100),
  PROPVALUE VARCHAR2(4000),
  INDX NUMBER(3) DEFAULT 0,
  CONSTRAINT CAS_CASECASEPROP_CASE_FK FOREIGN KEY (CASECASEID)
    REFERENCES CAS_CASECASE (CASECASEID) VALIDATE,
  CONSTRAINT CAS_CASECASEPROP_PK PRIMARY KEY (CASECASEID, PROPNAME, INDX) VALIDATE
);

-- classif module -------------------------------------------------

CREATE TABLE CLS_CLASS
(
  CLASSID VARCHAR2(32),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CONSTRAINT CLS_CLASS_PK PRIMARY KEY (CLASSID) VALIDATE
);

CREATE TABLE CLS_CLASSHISTORY
(
  CLASSID VARCHAR2(32),
  STARTDT CHAR(14),
  ENDDT CHAR(14),
  CLASSTYPEID VARCHAR2(64) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  SUPERCLASSID VARCHAR2(32),
  RDSCHEDULEID VARCHAR2(32),
  LOCATION VARCHAR2(32),
  HOMELOCATION VARCHAR2(32),
  OFFLINEDOWNLOAD CHAR(1),
  ACUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CHANGEREASON VARCHAR2(4000),
  PERIODID NUMBER(10),
  CONSTRAINT CLS_CLASSHISTORY_PK PRIMARY KEY (CLASSID, STARTDT) VALIDATE,
  CONSTRAINT CLS_CLASSHISTORY_CLASS_FK FOREIGN KEY (CLASSID)
    REFERENCES CLS_CLASS (CLASSID) VALIDATE,
  CONSTRAINT CLS_CLASSHISTORY_SUPER_FK FOREIGN KEY (SUPERCLASSID)
    REFERENCES CLS_CLASS (CLASSID) VALIDATE,
  CONSTRAINT CLS_PERIOD_SK UNIQUE (PERIODID);
);

CREATE TABLE CLS_CLASSHISTORYPROP
(
  PERIODID NUMBER(10),
  PROPNAME VARCHAR2(100),
  PROPINDEX NUMBER(5),
  PROPVALUE VARCHAR2(4000),
  CONSTRAINT CLS_CLASSHISTORYPROP_PK PRIMARY KEY (PERIODID, PROPNAME, PROPINDEX) VALIDATE,
  CONSTRAINT CLS_CLASSHISTORYPROP_PERIOD_FK FOREIGN KEY (PERIODID)
    REFERENCES CLS_CLASSHISTORY (PERIODID) ON DELETE CASCADE VALIDATE
);

DROP TABLE CLS_CLASSHISTORYPROP;

-- policy module --------------------------------------------------

CREATE TABLE POL_POLICY
(
  POLICYID NUMBER(10),
  TITLE VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(2000),
  POLICYTYPEID VARCHAR2(64),
  ACTDATEEXPR VARCHAR2(2000),
  ACTCONDITION VARCHAR2(2000),
  AUTOEXEC CHAR(1),
  MANDATE VARCHAR2(2000),
  EVALCODE VARCHAR2(100),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  CONSTRAINT POL_POLICY_PK PRIMARY KEY (POLICYID) VALIDATE,
  CONSTRAINT POL_POLICY_TYPE_FK FOREIGN KEY (POLICYTYPEID)
    REFERENCES DIC_TYPE (TYPEID) VALIDATE
);

CREATE TABLE POL_POLICYPROP
(
  POLICYID NUMBER(10),
  PROPNAME VARCHAR2(100),
  INDX NUMBER(3, 0) NOT NULL,
  PROPVALUE VARCHAR2(4000),
  CONSTRAINT POL_POLICYPROP_PK PRIMARY KEY (POLICYID, PROPNAME, INDX) VALIDATE,
  CONSTRAINT POL_POLICYPROP_POLICY_FK FOREIGN KEY (POLICYID)
    REFERENCES POL_POLICY (POLICYID) VALIDATE
);

CREATE TABLE POL_DISPHOLD
(
  DISPHOLDID NUMBER(10),
  TITLE VARCHAR2(2000),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  REASON VARCHAR2(2000),
  CONSTRAINT POL_DISPHOLD_PK PRIMARY KEY (DISPHOLDID) VALIDATE
);

CREATE TABLE POL_CLASSPOLICY
(
  CLASSPOLICYID NUMBER(10),
  CLASSID VARCHAR2(32) NOT NULL,
  POLICYID NUMBER(10) NOT NULL,
  DISPHOLDID NUMBER(10),
  REASON VARCHAR2(2000),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  STARTDATE CHAR(8),
  ENDDATE CHAR(8),
  CONSTRAINT POL_CLASSPOLICY_PK PRIMARY KEY (CLASSPOLICYID) VALIDATE,
  CONSTRAINT POL_CLASSPOLICY_DISPRULE_FK FOREIGN KEY (POLICYID)
    REFERENCES POL_POLICY (POLICYID) VALIDATE,
  CONSTRAINT POL_CLASSPOLICY_DISPHOLD_FK FOREIGN KEY (DISPHOLDID)
    REFERENCES POL_DISPHOLD (DISPHOLDID) VALIDATE
);

CREATE TABLE POL_CASEPOLICY
(
  CASEPOLICYID NUMBER(10),
  CASEID VARCHAR2(32) NOT NULL,
  POLICYID NUMBER(10) NOT NULL,
  ACTDATE CHAR(8),
  "STATE" CHAR(1) NOT NULL,
  DISPHOLDID NUMBER(10),
  REASON VARCHAR2(2000),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  APPROVALDT CHAR(14),
  APPROVALUSERID VARCHAR2(50),
  EXECUTIONDT CHAR(14),
  EXECUTIONUSERID VARCHAR2(50),
  EXECUTIONRESULT VARCHAR2(1000),
  CONSTRAINT POL_CASEPOLICY_PK PRIMARY KEY (CASEPOLICYID) VALIDATE,
  CONSTRAINT POL_CASEPOLICY_POLICY_FK FOREIGN KEY (POLICYID)
    REFERENCES POL_POLICY (POLICYID) VALIDATE,
  CONSTRAINT POL_CASEPOLICY_DISPHOLD_FK FOREIGN KEY (DISPHOLDID)
    REFERENCES POL_DISPHOLD (DISPHOLDID) VALIDATE
);

CREATE TABLE POL_DOCPOLICY
(
  DOCPOLICYID NUMBER(10),
  DOCID VARCHAR2(32) NOT NULL,
  POLICYID NUMBER(10) NOT NULL,
  ACTDATE CHAR(8),
  "STATE" CHAR(1) NOT NULL,
  DISPHOLDID NUMBER(10),
  REASON VARCHAR2(2000),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  APPROVALDT CHAR(14),
  APPROVALUSERID VARCHAR2(50),
  EXECUTIONDT CHAR(14),
  EXECUTIONUSERID VARCHAR2(50),
  EXECUTIONRESULT VARCHAR2(1000),
  CONSTRAINT POL_DOCPOLICY_PK PRIMARY KEY (DOCPOLICYID) VALIDATE,
  CONSTRAINT POL_DOCPOLICY_POLICY_FK FOREIGN KEY (POLICYID)
    REFERENCES POL_POLICY (POLICYID) VALIDATE,
  CONSTRAINT POL_DOCPOLICY_DISPHOLD_FK FOREIGN KEY (DISPHOLDID)
    REFERENCES POL_DISPHOLD (DISPHOLDID) VALIDATE
);


-- edu module -----------------------------------------------------

CREATE TABLE EDU_MATRICULA -- CHANGE TO EDU_INSCRIPTION
(
  MATCOD NUMBER(8, 0) NOT NULL, -- CHANGE TO INSCRIPTIONID
  CODI VARCHAR2(20), -- CHANGE TO CODE
  PERSCOD NUMBER(8, 0) NOT NULL, -- CHANGE TO PERSONID
  CURSCOD NUMBER(8, 0) NOT NULL, -- CHANGE TO COURSEID
  DATAINICI CHAR(8), -- CHANGE TO STARTDATE
  DATAFINAL CHAR(8), -- CHANGE TO ENDDATE
  CONSTRAINT EDU_MATRICULA_PK PRIMARY KEY(MATCOD)
);

CREATE TABLE EDU_MATPROP -- CHANGE TO EDU_INSCRIPTIONPROP
(
  MATCOD NUMBER(8, 0) NOT NULL, -- CHANGE TO INSCRIPTIONID
  PROPNOM VARCHAR2(32) NOT NULL, -- CHANGE TO PROPNAME
  PROPVAL VARCHAR2(200), -- CHANGE TO PROPVALUE
  CONSTRAINT EDU_MATPROP_PK PRIMARY KEY(MATCOD, PROPNOM)
);

CREATE TABLE EDU_CURS -- CHANGE TO EDU_COURSE
(
  CURSCOD NUMBER(8, 0) NOT NULL, -- CHANGE TO COURSEID
  CODI VARCHAR(20), -- CHANGE TO CODE
  NOM VARCHAR2(50) NOT NULL, -- CHANGE TO NAME
  CENTRECOD NUMBER(8, 0) NOT NULL, -- CHANGE TO CENTERID
  CONSTRAINT EDU_CURS_PK PRIMARY KEY(CURSCOD)
);

CREATE TABLE EDU_CENTRE -- CHANGE TO EDU_SCHOOL
(
  CENTRECOD NUMBER(8, 0) NOT NULL, -- CHANGE TO SCHOOLID
  CODI VARCHAR(20), -- CHANGE TO CODE
  NOM VARCHAR2(50) NOT NULL, -- CHANGE TO NAME
  CONSTRAINT EDU_CENTRE_PK PRIMARY KEY(CENTRECOD)
);

-- translation module -----------------------------------------------------

CREATE TABLE TRN_TRANSLATION
(
  TRANSID CHAR(36),
  "LANGUAGE" CHAR(2) NOT NULL,
  "TEXT" VARCHAR2(4000) NOT NULL,
  "TRANSLATION" VARCHAR2(4000),
  "STATE" CHAR(1) NOT NULL,
  GRP VARCHAR2(128), -- UNUSED
  CREATIONDT CHAR(14),
  MODIFYDT CHAR(14),
  READDT CHAR(14),
  MODIFYUSERID VARCHAR2(50),
  CONSTRAINT "TRN_TRANSLATION_PK" PRIMARY KEY(TRANSID)
);

CREATE TABLE TRN_TRANSLATIONGROUP
(
  TRANSID CHAR(36 BYTE),
	GRP VARCHAR2(64 BYTE),
  CONSTRAINT "TRN_TRANSLATIONGROUP_PK" PRIMARY KEY(TRANSID, GRP),
  CONSTRAINT "TRN_TRANSGROUP_TRANS_FK" FOREIGN KEY (TRANSID)
    REFERENCES TRN_TRANSLATION (TRANSID) VALIDATE
);

CREATE INDEX IDX_TRN_TEXT ON TRN_TRANSLATION ("TEXT");
CREATE INDEX IDX_TRN_TRANSLATION ON TRN_TRANSLATION ("TRANSLATION");
CREATE INDEX IDX_TRN_GROUP ON TRN_TRANSLATION ("GRP");
CREATE INDEX IDX_TRN_READDT ON TRN_TRANSLATION (READDT);
CREATE INDEX IDX_TRN_MODIFYDT ON TRN_TRANSLATION (MODIFYDT);

-- workflow module -----------------------------------------------------

CREATE TABLE WFW_INSTANCE
(
  INSTANCEID NUMBER(10, 0) NOT NULL,
  WORKFLOW VARCHAR2(50) NOT NULL,
  EVENTCOUNT NUMBER(10, 0) NOT NULL,
  PROCESSABLE CHAR(1),
  STARTDT CHAR(14),
  CONSTRAINT WFW_INSTANCE_PK PRIMARY KEY (INSTANCEID) ENABLE
);

CREATE TABLE WFW_VARIABLE
(
  INSTANCEID NUMBER NOT NULL,
  NAME VARCHAR2(64) NOT NULL,
  TYPE CHAR(1) NOT NULL,
  VALUE VARCHAR2(4000),
  CONSTRAINT WFW_VARIABLE_PK PRIMARY KEY (INSTANCEID,NAME) ENABLE,
  CONSTRAINT WFW_VARIABLE_INSTANCE_FK FOREIGN KEY (INSTANCEID)
    REFERENCES WFW_INSTANCE (INSTANCEID) ENABLE
);

CREATE TABLE WFW_EVENT
(
  INSTANCEID NUMBER(10, 0) NOT NULL,
  EVENTNUM NUMBER(10, 0) NOT NULL,
  DISPATCHED CHAR(1),
  EVENTDATE CHAR(8) NOT NULL,
  EVENTHOUR CHAR(6) NOT NULL,
  ACTOR VARCHAR2(50),
  CONSTRAINT WFW_EVENT_PK PRIMARY KEY (INSTANCEID,EVENTNUM) ENABLE,
  CONSTRAINT WFW_EVENT_INSTANCE_FK FOREIGN KEY (INSTANCEID)
    REFERENCES WFW_INSTANCE (INSTANCEID) ENABLE
);

CREATE TABLE WFW_EVENTVAR
(
  INSTANCEID NUMBER(10, 0) NOT NULL,
  EVENTNUM NUMBER(10, 0) NOT NULL,
  NAME VARCHAR2(64) NOT NULL,
  TYPE CHAR(1) NOT NULL,
  OLDVALUE VARCHAR2(4000),
  NEWVALUE VARCHAR2(4000),
  CONSTRAINT WFW_EVENTVAR_PK PRIMARY KEY (INSTANCEID,EVENTNUM,NAME) ENABLE,
  CONSTRAINT WFW_EVENTVAR_EVENT_FK FOREIGN KEY (INSTANCEID,EVENTNUM)
    REFERENCES WFW_EVENT (INSTANCEID,EVENTNUM) ENABLE
);

CREATE TABLE WFW_TIMER
(
  INSTANCEID NUMBER(10, 0) NOT NULL,
  DATETIME CHAR(14) NOT NULL,
  CONSTRAINT "WFW_TIMER_PK" PRIMARY KEY(INSTANCEID, DATETIME)
);

CREATE INDEX WFW_EVENTDATE_IDX ON WFW_EVENT ("EVENTDATE");
CREATE INDEX WFW_VARIABLE_VALUE_IDX ON WFW_VARIABLE ("VALUE");
CREATE INDEX WFW_VARIABLE_SEC_IDX on WFW_VARIABLE (TRIM(SUBSTR("VALUE", 20)));

-- kernel module (compatible with Matrix-1) --------------------------

CREATE TABLE NCL_SALA
(
  DOMCOD NUMBER(8, 0) NOT NULL,
  SALACOD NUMBER(4, 0) NOT NULL,
  SALADESC VARCHAR2(100),
  CAPACITAT NUMBER(8, 0),
  IMATGE VARCHAR2(200),
  TIPSALA NUMBER(4, 0),
  SUPERFICIE NUMBER(10, 3),
  TELEFON VARCHAR2(15),
  FAX VARCHAR2(15),
  EMAIL VARCHAR2(100),
  HORARI VARCHAR2(200),
  OBSERV VARCHAR2(200),
  ROOMTYPEID VARCHAR2(64),
  SPACEID VARCHAR(20),
  CONSTRAINT PK_SALA PRIMARY KEY(DOMCOD,SALACOD) ENABLE,
  CONSTRAINT FK_SALA_DOMICILI FOREIGN KEY(DOMCOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_DOMICILI(DOMCOD) ENABLE
);

CREATE TABLE NCL_PERSONPERSON
(
  PERSONPERSONID NUMBER(10),
  PERSONID NUMBER(8, 0),
  RELPERSONID NUMBER(8, 0),
  COMMENTS VARCHAR2(200),
  PERSONPERSONTYPEID VARCHAR2(64)
  CONSTRAINT NCL_PERSONPERSON_PERSON_FK FOREIGN KEY (PERSONID)
    REFERENCES <SCHEMA_GENESYS5>.NCL_PERSON (PERSCOD) VALIDATE,
  CONSTRAINT NCL_PERSONPERSON_PK PRIMARY KEY (PERSONPERSONID) VALIDATE
);

-- agenda module (compatible with Matrix-1) -------------------------------

CREATE TABLE AGD_TIPUSESDEVENIMENT
(
  TIPESDEVCOD NUMBER(4, 0) NOT NULL,
  TIPESDEVNOM VARCHAR2(50),
  COLORRGB CHAR(6),
  IMATGE VARCHAR2(100),
  ESDEVVNUM NUMBER(8, 0),
  ROLVISCOD VARCHAR2(14),
  ROLMODCOD VARCHAR2(14),
  FORMATIMPR CHAR(1),
  ACTIU CHAR(1),
  COMPACTAR CHAR(1),
  CONSTRAINT PK_AGD_TIPUSESDEVENIMENT PRIMARY KEY (TIPESDEVCOD) ENABLE
);

CREATE TABLE AGD_TIPESDEVTEMA
(
  TIPESDEVCOD NUMBER(4, 0) NOT NULL,
  TEMACOD NUMBER(4, 0) NOT NULL,
  CONSTRAINT PK_TIPESDEVTEMA PRIMARY KEY (TIPESDEVCOD,TEMACOD) ENABLE,
  CONSTRAINT FK_TIPESDTE_TIPESDEV FOREIGN KEY (TIPESDEVCOD)
    REFERENCES AGD_TIPUSESDEVENIMENT(TIPESDEVCOD) ENABLE
);

CREATE TABLE AGD_ESDEVENIMENT
(
  TIPESDEVCOD NUMBER(4, 0) NOT NULL,
  ESDEVCOD NUMBER(8, 0) NOT NULL,
  ESDEVNOM VARCHAR2(100),
  LLOCCOD NUMBER(8, 0),
  DATAINICI CHAR(8) NOT NULL,
  HORAINICI CHAR(6),
  DATAFINAL CHAR(8) NOT NULL,
  HORAFINAL CHAR(6),
  URL VARCHAR2(200),
  OBSERV VARCHAR2(1000),
  STDUGR CHAR(20),
  STDUMOD CHAR(20),
  STDDGR CHAR(8),
  STDDMOD CHAR(8),
  STDHGR CHAR(6),
  STDHMOD CHAR(6),
  PTIPESDEVCOD NUMBER(4, 0),
  PESDEVCOD NUMBER(8, 0),
  TIPRELPARE NUMBER(4, 0),
  CONTINUITAT CHAR(1),
  VISIBLEASSIST CHAR(1),
  OBSERVOCUL VARCHAR2(2000),
  EVENTTYPEID VARCHAR2(64),
  TEXT BLOB,
  CONSTRAINT PK_ESDEVENIMENT PRIMARY KEY (ESDEVCOD) ENABLE
);

CREATE TABLE AGD_ESDEVTEMA
(
  TIPESDEVCOD NUMBER(4, 0),
  ESDEVCOD NUMBER(8, 0) NOT NULL,
  TEMACOD NUMBER(4, 0) NOT NULL,
  CONSTRAINT PK_ESDEVTEMA PRIMARY KEY (ESDEVCOD,TEMACOD) ENABLE,
  CONSTRAINT FK_ESDEVTEMA_ESDEV FOREIGN KEY (ESDEVCOD)
    REFERENCES AGD_ESDEVENIMENT (ESDEVCOD) ENABLE
);



CREATE TABLE AGD_ATRIBESDEVENIMENT
(
  TIPESDEVCOD NUMBER(4, 0),
  ESDEVCOD NUMBER(8, 0) NOT NULL,
  ATRIBNOM VARCHAR2(20) NOT NULL,
  VALOR VARCHAR2(100),
  CONSTRAINT PK_ATRIBESDEV PRIMARY KEY (ESDEVCOD,ATRIBNOM) ENABLE
);

CREATE TABLE AGD_ASSISTIR
(
  TIPESDEVCOD NUMBER(4, 0),
  ESDEVCOD NUMBER(8, 0) NOT NULL,
  PERSCOD NUMBER(8, 0) NOT NULL,
  ROL VARCHAR2(50),
  PRESENTAT CHAR(1),
  OBSERV VARCHAR2(200),
  INCOGNIT CHAR(1),
  ATTENDANTTYPEID VARCHAR2(64),
  CONSTRAINT PK_ASSISTIR PRIMARY KEY(ESDEVCOD,PERSCOD) ENABLE,
  CONSTRAINT FK_ASSISTIR_ESDEV FOREIGN KEY (ESDEVCOD)
    REFERENCES AGD_ESDEVENIMENT (ESDEVCOD) ENABLE
);

CREATE TABLE AGD_ESDEVLLOC
(
  TIPESDEVCOD NUMBER(4, 0),
  ESDEVCOD NUMBER(8, 0) NOT NULL,
  NUMORDRE NUMBER(4, 0) NOT NULL,
  PAISCOD NUMBER(4, 0) NOT NULL,
  PROVCOD NUMBER(4, 0),
  MUNICOD NUMBER(4, 0),
  CARCOD NUMBER(8, 0),
  DOMCOD NUMBER(8, 0),
  SALACOD NUMBER(5, 0),
  OBSERV VARCHAR2(200),
  NUMERO CHAR(4),
  CONSTRAINT PK_ESDEVLLOC PRIMARY KEY(ESDEVCOD,NUMORDRE) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_SALA FOREIGN KEY(DOMCOD,SALACOD)
    REFERENCES NCL_SALA(DOMCOD,SALACOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_CARRER FOREIGN KEY(PAISCOD,PROVCOD,MUNICOD,CARCOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_CARRER(PAISCOD,PROVCOD,MUNICOD,CARCOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_ESDEV FOREIGN KEY(ESDEVCOD)
    REFERENCES AGD_ESDEVENIMENT(ESDEVCOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_MUNICIPI FOREIGN KEY(PAISCOD,PROVCOD,MUNICOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_MUNICIPI(PAISCOD,PROVCOD,MUNICOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_DOMICILI FOREIGN KEY(DOMCOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_DOMICILI(DOMCOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_PROVINCIA FOREIGN KEY(PAISCOD,PROVCOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_PROVINCIA(PAISCOD,PROVCOD) ENABLE,
  CONSTRAINT FK_ESDEVLLOC_PAIS FOREIGN KEY(PAISCOD)
    REFERENCES <SCHEMA_GENESYS5>.NCL_PAIS(PAISCOD) ENABLE
);

CREATE TABLE AGD_DOCUMENT
(
  EVENTDOCID NUMBER(10),
  EVENTID NUMBER(10),
  DOCID NUMBER(10),
  CREATIONDT CHAR(14),
  CREATIONUSERID VARCHAR2(50),
  CHANGEDT CHAR(14),
  CHANGEUSERID VARCHAR2(50),
  EVENTDOCTYPEID VARCHAR2(64),
  COMMENTS VARCHAR2(200),
  CONSTRAINT AGD_DOCUMENT_PK PRIMARY KEY (EVENTID, DOCID) VALIDATE
);

-- Feed module --

CREATE TABLE AJUNTAMENT.FED_FOLDER
(
  FOLDERID NUMBER(10),
  "NAME" VARCHAR2(1000) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  ICONDOCID NUMBER(10),
  "ALIAS" VARCHAR2(100),
  PARENTFOLDERID NUMBER(10),
  DEFAULTENTRYCOUNT NUMBER(5),
  CONSTRAINT FED_FOLDER_PK PRIMARY KEY (FOLDERID) VALIDATE,
  CONSTRAINT FOLDER_PARENTFOLDER_PK 
    FOREIGN KEY (PARENTFOLDERID) REFERENCES AJUNTAMENT.FED_FOLDER(FOLDERID) VALIDATE
)

CREATE TABLE AJUNTAMENT.FED_FEED
(
  FEEDID NUMBER(10),
  "NAME" VARCHAR2(1000) NOT NULL,
  URL VARCHAR2(1000) NOT NULL,
  INTERNALURL VARCHAR2(1000) NOT NULL,
  REFRESHINTERVAL NUMBER(10) NOT NULL,
  REFRESHDT CHAR(14) NOT NULL,
  ENTRYLIFESPAN NUMBER(10),
  "TYPE" VARCHAR2(10) NOT NULL,
  ICONURL VARCHAR2(1000),
  CONSTRAINT FED_FEED_PK PRIMARY KEY (FEEDID) VALIDATE
)

CREATE TABLE AJUNTAMENT.FED_FEEDFOLDER
(
  FEEDID NUMBER(10),
  FOLDERID NUMBER(10),
  CONSTRAINT FED_FEEDFOLDER_PK PRIMARY KEY (FEEDID, FOLDERID) VALIDATE,
  CONSTRAINT FED_FEEDFOLDER_FEED_FK FOREIGN KEY (FEEDID)
    REFERENCES AJUNTAMENT.FED_FEED (FEEDID) VALIDATE,
  CONSTRAINT FED_FEEDFOLDER_FOLDER_FK FOREIGN KEY (FOLDERID)
    REFERENCES AJUNTAMENT.FED_FOLDER (FOLDERID) VALIDATE
)

CREATE TABLE AJUNTAMENT.FED_ENTRY
(
  ENTRYID NUMBER(10),
  FEEDID NUMBER(10),
  TITLE VARCHAR2(1000),
  URL VARCHAR2(1000) NOT NULL,
  DESCRIPTION BLOB,
  PUBDT CHAR(14) NOT NULL,
  "HASH" CHAR(32) NOT NULL,
  VISIBLE CHAR(1),
  CONSTRAINT FED_ENTRY_PK PRIMARY KEY (ENTRYID) VALIDATE,
  CONSTRAINT FED_ENTRY_FEED_FK FOREIGN KEY (FEEDID)
    REFERENCES AJUNTAMENT.FED_FEED (FEEDID) VALIDATE
)

-- CMS (new forest) module ---------------------------------------

CREATE TABLE CMS_WORKSPACE
(
  WORKSPACEID    NUMBER(10,0),
  NAME           VARCHAR2(100 BYTE),
  DESCRIPTION    VARCHAR2(4000 BYTE),
  CREATIONDT     CHAR(14 BYTE) NOT NULL ENABLE,
  CREATIONUSERID VARCHAR2(20 BYTE) NOT NULL ENABLE,
  REFWORKSPACEID NUMBER(10,0),
  CONSTRAINT CMS_WORKSPACE_PK PRIMARY KEY (WORKSPACEID) VALIDATE,
  CONSTRAINT CMS_WORKSPACE_REFWORKSPACE_FK FOREIGN KEY (REFWORKSPACEID) REFERENCES CMS_WORKSPACE (WORKSPACEID) VALIDATE
);


CREATE TABLE CMS_NODE
(
  WORKSPACEID NUMBER(10),
  NODEID NUMBER(10),
  PARENTNODEID NUMBER(10),
  IDX NUMBER(5) NOT NULL,
  "NAME" VARCHAR2(200),
  CHANGEDT CHAR(14) NOT NULL,
  CHANGEUSERID VARCHAR2(20) NOT NULL,
  SYNCDT CHAR(14),
  SYNCUSERID VARCHAR2(20),
  "PATH" VARCHAR2(1000),
  CONSTRAINT CMS_NODE_PK PRIMARY KEY (WORKSPACEID, NODEID) VALIDATE,
  CONSTRAINT CMS_NODE_WORKSPACE_FK FOREIGN KEY(WORKSPACEID)
    REFERENCES CMS_WORKSPACE(WORKSPACEID) VALIDATE,
  CONSTRAINT CMS_NODE_PARENTNODE_FK FOREIGN KEY(WORKSPACEID, PARENTNODEID)
    REFERENCES CMS_NODE(WORKSPACEID, NODEID) VALIDATE
);

CREATE TABLE CMS_PROPERTY
(
  WORKSPACEID NUMBER(10),
  NODEID NUMBER(10),
  "NAME" VARCHAR2(100),
  IDX NUMBER(5),
  "VALUE" VARCHAR2(4000) NOT NULL,
  CONSTRAINT CMS_PROPERTY_PK PRIMARY KEY (WORKSPACEID, NODEID, "NAME", IDX) VALIDATE,
  CONSTRAINT CMS_PROPERTY_NODE_FK FOREIGN KEY (WORKSPACEID, NODEID)
    REFERENCES CMS_NODE(WORKSPACEID, NODEID) VALIDATE
);

CREATE INDEX CMS_NODE_PARENT_IDX ON CMS_NODE (WORKSPACEID, PARENTNODEID);
CREATE INDEX CMS_PROPERTY_VALUE_IDX ON CMS_PROPERTY (VALUE);

-- New Forum module --------------------------------------------------

CREATE TABLE FRU_FORUM
(
  FORUMID         NUMBER(10,0),
  STARTDT         CHAR(14) NOT NULL,
  ENDDT           CHAR(14),
  "NAME"          VARCHAR2(200) NOT NULL,
  DESCRIPTION     VARCHAR2(4000),
  "TYPE"          CHAR(1) NOT NULL,
  EMAILFROM       VARCHAR2(100),
  EMAILTO         VARCHAR2(100),
  LASTINPUTINDEX  NUMBER(10,0) NOT NULL,
  LASTOUTPUTINDEX NUMBER(10,0) NOT NULL,
  GRP             VARCHAR2(50) NOT NULL,
  ADMINROLE       VARCHAR2(50) NOT NULL,
  MAXQUESTIONS    NUMBER(10,0) NOT NULL,
  CREATIONUSERID  VARCHAR2(20) NOT NULL,
  CREATIONDT      CHAR(14) NOT NULL,
  CHANGEUSERID    VARCHAR2(20) NOT NULL,
  CHANGEDT        CHAR(14) NOT NULL,
  CONSTRAINT FRU_FORUM_PK PRIMARY KEY (FORUMID) VALIDATE
);

CREATE TABLE FRU_QUESTION
(
  QUESTIONID      NUMBER(10,0),
  FORUMID         NUMBER(10,0) NOT NULL,
  TITLE           VARCHAR2(1000),
  TEXT            VARCHAR2(4000),
  READCOUNT       NUMBER(10,0) NOT NULL,
  VISIBLE         CHAR(1) NOT NULL,
  INPUTINDEX      NUMBER(10,0) NOT NULL,
  OUTPUTINDEX     NUMBER(10,0) NOT NULL,
  CREATIONUSERID  VARCHAR2(20) NOT NULL,
  CREATIONDT      CHAR(14) NOT NULL,
  CHANGEUSERID    VARCHAR2(20),
  CHANGEDT        CHAR(14),
  ACTIVITYDT      CHAR(14),
  CONSTRAINT FRU_QUESTION_PK PRIMARY KEY (QUESTIONID) VALIDATE,
  CONSTRAINT FRU_QUESTION_FORUM_FK FOREIGN KEY (FORUMID) REFERENCES FRU_FORUM(FORUMID) VALIDATE
);

CREATE TABLE FRU_ANSWER
(
  ANSWERID        NUMBER(10,0),
  QUESTIONID      NUMBER(10,0) NOT NULL,
  TEXT            VARCHAR2(4000),
  COMMENTS        VARCHAR2(4000),
  CREATIONUSERID  VARCHAR2(20) NOT NULL,
  CREATIONDT      CHAR(14) NOT NULL,
  CHANGEUSERID    VARCHAR2(20),
  CHANGEDT        CHAR(14),
  CONSTRAINT FRU_ANSWER_PK PRIMARY KEY (ANSWERID) VALIDATE,
  CONSTRAINT FRU_ANSWER_QUESTION_FK FOREIGN KEY (QUESTIONID) REFERENCES FRU_QUESTION(QUESTIONID) VALIDATE
);

-- User preferences management ---------------------------------------

CREATE TABLE WEB_PREFERENCES
(
  USRCOD CHAR(20) NOT NULL,
  "NAME" VARCHAR2(100) NOT NULL,
  IDX NUMBER(5) NOT NULL,
  "VALUE" VARCHAR2(100) NOT NULL,
  CONSTRAINT WEB_PREFERENCES_PK PRIMARY KEY (USRCOD, "NAME", IDX) VALIDATE
);

-- presence tables ------------------------------------------------

CREATE TABLE PCN_USER -- REPLACED BY PCN_WORKER
(
  PERSONID VARCHAR(20) NOT NULL,
  LOCKCOUNT NUMBER(8) NOT NULL,
  CONSTRAINT PCN_USER_PK PRIMARY KEY (PERSONID) VALIDATE
);

CREATE TABLE PCN_PRESENCE -- REPLACED BY PCN_ENTRY
(
  PERSONID VARCHAR(20) NOT NULL,
  ENTRYDT CHAR(14) NOT NULL,
  ENTRYTYPEID VARCHAR2(32) NOT NULL,
  DURATION NUMBER(8), -- SECONDS
  WORKEDTIME NUMBER(8), -- SECONDS
  BONUSTIME NUMBER(8), -- SECONDS
  MANIPULATED CHAR(1),
  REASON VARCHAR2(100),
  CREATIONDT CHAR(14) NOT NULL,
  IPADDRESS VARCHAR2(20),
  CONSTRAINT PCN_PRESENCE_PK PRIMARY KEY (PERSONID, ENTRYDT) VALIDATE
);

CREATE TABLE PCN_PARAMETER
(
  PARAMID VARCHAR2(50) NOT NULL,
  VALUE VARCHAR2(1000),
  CHANGEUSERID VARCHAR2(20),
  CHANGEDT CHAR(14),
  CONSTRAINT PCN_PARAMETER_PK PRIMARY KEY (PARAMID) VALIDATE
);

CREATE TABLE PCN_WORKER
(
  PERSONID VARCHAR2(20) NOT NULL,
  FULLNAME VARCHAR2(100) NOT NULL,
  VALPERSONID VARCHAR2(20),
  TEAM VARCHAR2(20),
  BONUSTIME NUMBER,
  CONSTRAINT PCN_WORKER_PK PRIMARY KEY (PERSONID) VALIDATE,
  CONSTRAINT FK_PCN_WORKER_VALIDATOR FOREIGN KEY (VALPERSONID)
    REFERENCES PCN_WORKER(PERSONID) ENABLE
);

CREATE TABLE PCN_ENTRYTYPE
(
  ENTRYTYPEID NUMBER NOT NULL,
  LABEL VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(1000),
  MAXWORKEDTIME NUMBER NOT NULL,
  REALWORK CHAR(1),
  POSITION NUMBER,
  ENABLED CHAR(1),
  COLOR CHAR(6),
  FILTER VARCHAR2(100),
  CODE CHAR(3),
  CONSOLIDABLE CHAR(1),
  ABSENCE CHAR(1),
  CONSTRAINT PCN_ENTRYTYPE_PK PRIMARY KEY (ENTRYTYPEID) VALIDATE
);

CREATE TABLE PCN_DAYTYPE
(
  DAYTYPEID NUMBER NOT NULL,
  LABEL VARCHAR2(100) NOT NULL,
  INTIME1 CHAR(6),
  OUTTIME1 CHAR(6),
  INTIME2 CHAR(6),
  OUTTIME2 CHAR(6),
  FLEX1 NUMBER,
  FLEX2 NUMBER,
  COLOR CHAR(6),
  CODE CHAR(3),
  HOLIDAYS CHAR(1) NOT NULL,
  REDUCTIONS CHAR(1) NOT NULL,
  CONSTRAINT PCN_DAYTYPE_PK PRIMARY KEY (DAYTYPEID) VALIDATE
);

CREATE TABLE PCN_WEEKTYPE
(
  WEEKTYPEID NUMBER NOT NULL,
  LABEL VARCHAR2(100) NOT NULL,
  MODAYTYPEID NUMBER,
  TUDAYTYPEID NUMBER,
  WEDAYTYPEID NUMBER,
  THDAYTYPEID NUMBER,
  FRDAYTYPEID NUMBER,
  SADAYTYPEID NUMBER,
  SUDAYTYPEID NUMBER,
  CONSTRAINT PCN_WEEKTYPE_PK PRIMARY KEY (WEEKTYPEID) VALIDATE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_MO FOREIGN KEY (MODAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_TU FOREIGN KEY (TUDAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_WE FOREIGN KEY (WEDAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_TH FOREIGN KEY (THDAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_FR FOREIGN KEY (FRDAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_SA FOREIGN KEY (SADAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_WEEKTYPE_DAYTYPE_SU FOREIGN KEY (SUDAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE
);

CREATE TABLE PCN_HOLIDAY 
(
  HOLIDAYID NUMBER,
	STARTDATE CHAR(8) NOT NULL, 
	ENDDATE CHAR(8) NOT NULL, 
	DESCRIPTION VARCHAR2(100), 
	OPTIONAL CHAR(1), 
	COLOR CHAR(6),
  CONSTRAINT PCN_HOLIDAY_PK PRIMARY KEY (HOLIDAYID) VALIDATE
);

CREATE TABLE PCN_REDUCTION
(
  REDUCTIONID NUMBER,
  STARTDATE CHAR(8) NOT NULL,
  ENDDATE CHAR(8) NOT NULL,
  DESCRIPTION VARCHAR2(100) NOT NULL,
  FACTOR NUMBER NOT NULL,
  CONSTRAINT PCN_REDUCTION_PK PRIMARY KEY (REDUCTIONID) VALIDATE
);

CREATE TABLE PCN_WORKERWEEK
(
  PERSONID VARCHAR2(20) NOT NULL,
  STARTDATE CHAR(8) NOT NULL,
  ENDDATE CHAR(8),
  WEEKTYPEID NUMBER NOT NULL,
  CONSTRAINT PCN_WORKERWEEK_PK PRIMARY KEY (PERSONID, STARTDATE) VALIDATE,
  CONSTRAINT FK_PCN_WORKERWEEK_WEEKTYPE FOREIGN KEY (WEEKTYPEID)
    REFERENCES PCN_WEEKTYPE(WEEKTYPEID) ENABLE
);

CREATE TABLE PCN_WORKERDAY
(
  PERSONID VARCHAR2(20) NOT NULL,
  WDATE CHAR(8) NOT NULL,
  DAYTYPEID NUMBER NOT NULL,
  CONSTRAINT PCN_WORKERDAY_PK PRIMARY KEY (PERSONID, WDATE) VALIDATE,
  CONSTRAINT FK_PCN_WORKERDAY_DAYTYPE FOREIGN KEY (DAYTYPEID)
    REFERENCES PCN_DAYTYPE(DAYTYPEID) ENABLE
);

CREATE TABLE PCN_WORKERGROUP
(
  PERSONID VARCHAR2(20) NOT NULL,
  RELPERSONID VARCHAR2(20) NOT NULL,
  POSITION NUMBER,
  CONSTRAINT PCN_WORKERGROUP_PK PRIMARY KEY (PERSONID, RELPERSONID) VALIDATE,
  CONSTRAINT PCN_WGROUP_PERSONID_FK FOREIGN KEY (PERSONID)
    REFERENCES PCN_WORKER(PERSONID) ENABLE,
  CONSTRAINT PCN_WGROUP_RELPERSONID_FK FOREIGN KEY (RELPERSONID)
    REFERENCES PCN_WORKER(PERSONID) ENABLE
);

CREATE TABLE PCN_ABSENCETYPE
(
  ABSTYPEID NUMBER,
  LABEL VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(1000),
  AUTHOR CHAR(1),
  JUSTIFY CHAR(1),
  ENABLED CHAR(1),
  COUNTERVISIBLE CHAR(1),
  HOLIDAY CHAR(1),
  COUNTING CHAR(1),
  CARRY CHAR(1),
  DEFTIME NUMBER,
  POSITION NUMBER,
  ENTRYTYPEID NUMBER,
  CONSTRAINT PCN_ABSENCETYPE_PK PRIMARY KEY (ABSTYPEID) VALIDATE,
  CONSTRAINT FK_ABSENCE_ENTRYTYPE FOREIGN KEY (ENTRYTYPEID)
    REFERENCES PCN_ENTRYTYPE(ENTRYTYPEID) ENABLE
);

CREATE TABLE PCN_ABSENCECOUNTER
(
  PERSONID VARCHAR(20) NOT NULL,
  YEAR CHAR(4) NOT NULL,
  ABSTYPEID NUMBER NOT NULL,
  REMAININGTIME NUMBER NOT NULL,
  TOTALTIME NUMBER NOT NULL,
  CONSTRAINT PCN_ABSENCECOUNTER_PK PRIMARY KEY (PERSONID, YEAR, ABSTYPEID) VALIDATE,
  CONSTRAINT FK_PCN_ABSCOUNTER_WORKER FOREIGN KEY (PERSONID)
    REFERENCES PCN_WORKER(PERSONID) ENABLE,
  CONSTRAINT FK_ABSCOUNTER_ABSTYPE FOREIGN KEY (ABSTYPEID)
    REFERENCES PCN_ABSENCETYPE(ABSTYPEID) ENABLE
);

CREATE TABLE PCN_ABSENCE
(
  ABSID NUMBER NOT NULL,
  PERSONID VARCHAR2(20) NOT NULL,
  ABSTYPEID NUMBER NOT NULL,
  STARTDT CHAR(14) NOT NULL,
  ENDDT CHAR(14) NOT NULL,
  REASON VARCHAR2(200),
  STATUS CHAR(1),
  STATUSDETAIL VARCHAR2(50),
  REQDAYS NUMBER,
  CONSOLDAYS NUMBER,
  REQTIME NUMBER,
  CONSOLTIME NUMBER,
  INSTANCEID VARCHAR2(20),
  ABSDOCID VARCHAR2(20),
  JUSTDOCID VARCHAR2(20),
  CONSTRAINT PCN_ABSENCE_PK PRIMARY KEY (ABSID) VALIDATE,
  CONSTRAINT FK_PCN_ABSENCE_WORKER FOREIGN KEY (PERSONID)
    REFERENCES PCN_WORKER(PERSONID) ENABLE,
  CONSTRAINT FK_PCN_ABSENCE_ABSENCETYPE FOREIGN KEY (ABSTYPEID)
    REFERENCES PCN_ABSENCETYPE(ABSTYPEID) ENABLE
);

CREATE TABLE PCN_ENTRY
(
  PERSONID VARCHAR(20) NOT NULL,
  STARTDT CHAR(14) NOT NULL,
  ENDDT CHAR(14),
  ENTRYTYPEID NUMBER NOT NULL,
  DURATION NUMBER(8), -- SECONDS
  WORKEDTIME NUMBER(8), -- SECONDS
  BONUSTIME NUMBER(8), -- SECONDS
  MANIPULATED CHAR(1),
  REASON VARCHAR2(200),
  CREATIONDT CHAR(14) NOT NULL,
  CHANGEDT CHAR(14) NOT NULL,
  CREATIONUSERID VARCHAR2(20) NOT NULL,
  CHANGEUSERID VARCHAR2(20) NOT NULL,
  IPADDRESS VARCHAR2(50),
  ABSID NUMBER,
  PREVENTRYTYPEID NUMBER,
  CONSTRAINT PCN_ENTRY_PK PRIMARY KEY (PERSONID, STARTDT) VALIDATE,
  CONSTRAINT FK_PCN_ENTRY_ENTRYTYPE FOREIGN KEY (ENTRYTYPEID)
    REFERENCES PCN_ENTRYTYPE(ENTRYTYPEID) ENABLE,
  CONSTRAINT FK_PCN_ENTRY_ABSENCE FOREIGN KEY (ABSID)
    REFERENCES PCN_ABSENCE(ABSID) ENABLE
);


---------------------------------------------------------------------

--grant CTXAPP to <SCHEMA>;
grant select on CNT_EXTERNAL to ctxsys;
grant select on CNT_INTERNAL to ctxsys;

---- CREAR INDEX CONTEXTUAL 

--DROP INDEX CTXSYS.CNT_EXTERNAL_IDX;
--DROP INDEX CTXSYS.CNT_INTERNAL_IDX;
--begin
--ctx_ddl.drop_preference('EXT_DOCS');
--end;
--/

--begin
--ctx_ddl.drop_preference('<SCHEMA>.EXT_DOCS');
--end;
--/
 
begin 
  ctx_ddl.create_preference('EXT_DOCS','URL_DATASTORE');
  ctx_ddl.set_attribute('EXT_DOCS','Timeout','300');
end;
/

CREATE INDEX CNT_EXTERNAL_IDX ON CNT_EXTERNAL(URL)
  INDEXTYPE IS CTXSYS.CONTEXT ONLINE
  PARAMETERS ('datastore EXT_DOCS filter ctxsys.auto_filter format column fmt');

begin
  ctx_ddl.create_preference('INT_DOCS','DIRECT_DATASTORE');
end;
/

begin
  ctx_ddl.create_preference('INT_DOCS_STORE','BASIC_STORAGE');
  ctx_ddl.set_attribute('INT_DOCS_STORE','I_TABLE_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 10M next 10M)');
  ctx_ddl.set_attribute('INT_DOCS_STORE', 'K_TABLE_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 10M next 10M)');
  ctx_ddl.set_attribute('INT_DOCS_STORE', 'R_TABLE_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 1M) lob (data) store as (cache)');
  ctx_ddl.set_attribute('INT_DOCS_STORE', 'N_TABLE_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 1M)');
  ctx_ddl.set_attribute('INT_DOCS_STORE', 'I_INDEX_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 1M) compress 2');
  ctx_ddl.set_attribute('INT_DOCS_STORE', 'P_TABLE_CLAUSE',
  'tablespace <TABLESPACE> storage (initial 1M)');
end;
/
CREATE INDEX CNT_INTERNAL_IDX ON CNT_INTERNAL(DATA)
  INDEXTYPE IS CTXSYS.CONTEXT ONLINE
  PARAMETERS ('datastore INT_DOCS filter ctxsys.auto_filter storage INT_DOCS_STORE format column fmt');

CREATE VIEW CNT_INDEX_ERROR AS 
  SELECT d.docid, d.doctypeid, d.title, c.mimetype, c.contentsize, 
         err_timestamp, err_text, i.uuid, i.fmt
  FROM ctxsys.dr$index_error e, cnt_internal i, dom_document d, cnt_content c
  WHERE e.err_textkey = i.rowid and d.contentid = i.uuid and i.uuid = c.uuid
  ORDER BY err_timestamp desc

CREATE INDEX I_ESDEVENIMENT_DATAINICI ON AGD_ESDEVENIMENT (DATAINICI ASC);

insert into ORG_USUARI (usrcod, usrpass, perscod) values ('admin', '!!,+zF\{', 0);
insert into ORG_USUARI (usrcod, usrpass, perscod) values ('neo', '!!,+zF\{', 0);

insert into APL_ROL (rolcod, roldesc) values ('config', 'Configuration role');
insert into APL_ROLUSR (usrcod, rolcod) values ('admin','config');

insert into cms_workspace(workspaceid,name,description,creationdt,creationuserid) values (1,'Producció','Web corporativa en producció','20100701080000','neo');
insert into cms_node(workspaceid,nodeid,parentnodeid,idx,name,changedt,changeuserid,syncdt,syncuserid,"PATH") values (1,1,null,1,'Root','20100701080000','neo',null,null,'/1/');

INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('POL_POLICY', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('POL_DISPHOLD', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('POL_CLASSPOLICY', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('POL_CASEPOLICY', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('POL_DOCPOLICY', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cms.project', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('FRU_FORUM', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('FRU_QUESTION', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('FRU_ANSWER', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('survey.survey', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('DSP_CLASSDISP', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('DSP_CASEDISP', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('DSP_DOCDISP', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('DSP_DISPRULE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('DSP_DISPHOLD', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_PETICIO', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('edu.inscription', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INF_NEW', 1);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('edu.course', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('edu.school', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('doc2.document', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_OBJECTE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_MODELOBJ', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_TIPUSOBJ', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_TIPTASCOD', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('INV_TIPUSPRIORITAT', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('workflow.instance', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('SUR_SURVEY', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.case', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.intervention', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.caseListItem', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.casePerson', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.caseProblem', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.caseDemand', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.caseCase', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('FRS_NODE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('FRS_SESSION', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('recmobles.codi', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('doc.document', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cms.workspace', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cms.node', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('feed.folder', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('feed.feed', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('feed.entry', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('dic.enumTypeItem', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('cases.intProb', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_ABSENCE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_ABSENCETYPE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_WEEKTYPE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_DAYTYPE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_REDUCTION', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_ENTRYTYPE', 0);
INSERT INTO TABLESEQ (COUNTER, VALUE) VALUES ('PCN_HOLIDAY', 0);
COMMIT;