CREATE SEQUENCE LOG_FILE_SEQUENCE
 INCREMENT BY 1
 START WITH 1
 MAXVALUE 999999
 NOCACHE
 NOCYCLE;

CREATE TABLE LOG_FILE
(
  FILEID      NUMBER(10,0),
  FILENAME    VARCHAR2(1000) NOT NULL,
  LABEL       VARCHAR2(200),
  DATETIME    CHAR(14) NOT NULL,
  ACCEPTED    NUMBER(10,0),
  IGNORED     NUMBER(10,0),
  WARNINGS    NUMBER(10,0),
  ERRORS      NUMBER(10,0),
  DURATION    NUMBER(10,0),
  CONSTRAINT LOG_FILE_PK PRIMARY KEY (FILEID) VALIDATE
);

CREATE TABLE LOG_ACCESS
(
  FILEID      NUMBER(10,0),
  NUM         NUMBER(10,0),
  DATETIME    CHAR(14) NOT NULL,
  USERID      VARCHAR2(100) NOT NULL,
  ACT         VARCHAR2(1000) NOT NULL,
  IP          VARCHAR2(20),
  CONSTRAINT LOG_ACCESS_PK PRIMARY KEY (FILEID, NUM) VALIDATE,
  CONSTRAINT LOG_ACCESS_FILE_FK FOREIGN KEY (FILEID)
    REFERENCES LOG_FILE(FILEID) ON DELETE CASCADE VALIDATE
);

CREATE TABLE LOG_PROPERTY
(
  FILEID      NUMBER(10,0),
  NUM         NUMBER(10,0),
  PROPNAME    VARCHAR2(100) NOT NULL,
  PROPVALUE   VARCHAR2(4000) NOT NULL,
  CONSTRAINT LOG_PROPERTY_PK PRIMARY KEY (FILEID, NUM, PROPNAME) VALIDATE,
  CONSTRAINT LOG_PROPERTY_ACCESS_FK FOREIGN KEY (FILEID, NUM)
    REFERENCES LOG_ACCESS(FILEID, NUM) ON DELETE CASCADE VALIDATE
);

CREATE INDEX LOG_FILE_DATETIME_IDX ON LOG_FILE (DATETIME);
CREATE INDEX LOG_ACCESS_DATETIME_IDX ON LOG_ACCESS (DATETIME);
CREATE INDEX LOG_ACCESS_USERID_IDX ON LOG_ACCESS (USERID);
CREATE INDEX LOG_ACCESS_ACT_IDX ON LOG_ACCESS (ACT);
CREATE INDEX LOG_ACCESS_USERID_DT_IDX ON LOG_ACCESS (USERID, DATETIME);
CREATE INDEX LOG_ACCESS_ACT_DT_IDX ON LOG_ACCESS (ACT, DATETIME);
CREATE INDEX LOG_PROPERTY_PROPNAME_IDX ON LOG_PROPERTY (PROPNAME);
CREATE INDEX LOG_PROPERTY_PROPVALUE_IDX ON LOG_PROPERTY (PROPVALUE);
CREATE INDEX LOG_PROPERTY_NAME_VALUE_IDX ON LOG_PROPERTY (PROPNAME, PROPVALUE);
CREATE INDEX LOG_ACCESS_MONTH_IDX ON
  LOG_ACCESS (SUBSTR(DATETIME, 1, 6), FILEID, NUM);
CREATE INDEX LOG_ACCESS_MONTH_USERID_IDX
  ON LOG_ACCESS (SUBSTR(DATETIME, 1, 6), USERID, FILEID, NUM);
