INSERT INTO CMS_WORKSPACE
(WORKSPACEID, NAME, DESCRIPTION, CREATIONDT, CREATIONUSERID, REFWORKSPACEID)
VALUES
('1', 'Producció', 'Web corporativa en producció', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'admin', NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '1', NULL, '1', 'Arrel', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '2', '1', '1', 'Matrix', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '3', '2', '1', 'Diccionari', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '4', '3', '1', 'Dic General', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '5', '3', '2', 'Dic Propietats', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '6', '3', '3', 'Dic Seguretat', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '7', '2', '5', 'Document', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '8', '7', '1', 'Doc Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '16', '7', '2', 'Doc Contingut', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '17', '7', '-1', 'Doc Persones', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '21', '16', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '22', '7', '4', 'Doc Versions', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '23', '7', '5', 'Doc Seguretat', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '24', '7', '6', 'Doc Polítiques', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '25', '2', '10', 'Usuari', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '26', '25', '1', 'Usuari Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '27', '25', '2', 'Usuari Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '28', '2', '11', 'Usuari', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '29', '28', '1', 'Usuari Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '30', '28', '2', 'Usuari Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '31', '28', '3', 'Usuari Principal', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '32', '2', '2', 'Diccionari', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '33', '32', '-1', 'Dic General', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '34', '32', '-1', 'Dic Propietats', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '35', '32', '-1', 'Dic Seguretat', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '36', '7', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '37', '2', '12', 'Persones', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '38', '37', '1', 'Pesona Identificacio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '39', '2', '6', 'Expedients', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '40', '39', '1', 'Case.Descripcio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '41', '39', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '42', '39', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '43', '39', '4', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '44', '39', '5', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '45', '39', '6', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '46', '39', '7', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '47', '2', '13', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '48', '2', '14', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '49', '2', '15', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '50', '2', '16', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '51', '2', '17', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '52', '37', '2', 'Pesona Identificacio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '53', '37', '3', 'Pesona Identificacio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '54', '37', '4', 'Pesona Identificacio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '55', '37', '5', 'Pesona Identificacio', to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '56', '47', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '57', '47', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '58', '47', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '59', '2', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '60', '59', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '61', '59', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '62', '59', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '63', '2', '4', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '64', NULL, '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '65', '64', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '66', '1', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '67', '1', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '68', '1', '4', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '69', '68', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '70', '68', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '71', '64', '2', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '72', NULL, '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '73', '72', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '74', '72', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '75', '72', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '76', '72', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '77', '72', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '78', '64', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '79', '64', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '80', '64', '-1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '81', '64', '3', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '82', '2', '7', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '83', '82', '1', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '84', '2', '8', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_NODE
(WORKSPACEID, NODEID, PARENTNODEID, IDX, NAME, CHANGEDT, CHANGEUSERID, SYNCDT, SYNCUSERID)
VALUES
('1', '85', '2', '9', NULL, to_char(sysdate, 'YYYYMMDDHH24MISS'), 'neo', NULL, NULL);

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'imageId', '1', '2');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'footerEmail', '1', 'informacio@ajuntament.cat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'roles.update', '1', 'WEBMASTER');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'translationEnabled', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'footerInfo', '1', 'Matrix 2');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'renderWebsMenu', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'render.expression', '1', '@description;$; ;@_nodeid; ;@label');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'editRoles', '1', 'SECURITY_ADMIN');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'iconURL', '1', '/frames/santfeliu/images/pic-projectes.gif');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'frame', '1', 'santfeliu');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'relation.nodePropertyName', '1', '_nodeid');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'mid', '1', 'root');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'template', '1', 'generic1');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'topweb', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'label', '1', 'Plana principal');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '1', 'relation.objectPropertyName', '1', 'relation');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'classSearchMid', '1', '59');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'showHeader', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'provinceSearchMid', '1', '49');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'description', '1', 'Matrix');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'section', '1', 'matrix');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'typeSearchMid', '1', '3');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'label', '1', 'Matrix');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'userSearchMid', '1', '25');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'personSearchMid', '1', '37');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'roleSearchMid', '1', '28');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'topweb', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'documentSearchMid', '1', '7');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'addressSearchMid', '1', '47');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'caseSearchMid', '1', '39');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'streetSearchMid', '1', '51');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'countrySearchMid', '1', '48');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'citySearchMid', '1', '50');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '2', 'policySearchMid', '1', '82');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'oc.objectBean', '1', 'typeBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'label', '1', 'Diccionari llista');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'oc.searchBean', '1', 'typeSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'typeTreeMid', '1', '32');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'oc.objectTitle', '1', 'Type');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'action', '1', '#{typeSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '3', 'oc.searchTitle', '1', 'Diccionari');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '4', 'oc.pageBean', '1', 'typeMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '4', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '4', 'label', '1', 'General');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '5', 'label', '1', 'Propietats');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '5', 'oc.pageBean', '1', 'typePropertiesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '5', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '6', 'label', '1', 'Seguretat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '6', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '6', 'oc.pageBean', '1', 'typeACLBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'label', '1', 'Documents');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'oc.objectTitle', '1', 'Document');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'disableRoles', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'action', '1', '#{documentSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.class.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.completeState.check', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.recordState.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.docId.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.deletedState.check', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.recordState.check', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.draftState.check', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.completeState.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.version.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.deletedState.render', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.draftState.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.type.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'filterPanel.contentId.render', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'oc.searchTitle', '1', 'Cercador de documents');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'oc.objectBean', '1', 'document2Bean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'oc.searchBean', '1', 'documentSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '7', 'body.urlColumn.render', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '8', 'oc.pageBean', '1', 'documentMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '8', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '8', 'label', '1', 'Principal');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '16', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '16', 'label', '1', 'Contingut');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '16', 'oc.pageBean', '1', 'documentContentBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '17', 'oc.pageBean', '1', 'documentPersonsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '17', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '17', 'label', '1', 'Persones');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '22', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '22', 'oc.pageBean', '1', 'documentVersionsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '22', 'label', '1', 'Versions');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '23', 'label', '1', 'Seguretat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '23', 'oc.pageBean', '1', 'documentACLBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '24', 'document_analizer', '1', 'document_analizer.xml');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '24', 'label', '1', 'Politiques');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '24', 'oc.pageBean', '1', 'documentPoliciesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '25', 'label', '1', 'Usuari');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '25', 'oc.objectBean', '1', 'userBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '25', 'action', '1', '#{userSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '25', 'oc.searchTitle', '1', 'Cercador d''usuaris');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '25', 'oc.searchBean', '1', 'userSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '26', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '26', 'oc.pageBean', '1', 'userMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '26', 'label', '1', 'Principal');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '27', 'oc.pageBean', '1', 'userRolesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '27', 'label', '1', 'Rols');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '27', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'userSearchMid', '1', '25');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'oc.searchTitle', '1', 'Cercador de rols');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'label', '1', 'Rol');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'oc.searchBean', '1', 'roleSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'oc.objectBean', '1', 'roleBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '28', 'action', '1', '#{roleSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '29', 'oc.pageBean', '1', 'roleMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '29', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '29', 'label', '1', 'Principal');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '30', 'oc.pageBean', '1', 'roleRolesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '30', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '30', 'label', '1', 'Rols');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '31', 'oc.pageBean', '1', 'roleUsersBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '31', 'label', '1', 'Usuaris');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '31', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '32', 'oc.searchBean', '1', 'typeTreeBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '32', 'label', '1', 'Diccionari arbre');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '32', 'action', '1', '#{typeTreeBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '32', 'oc.searchTitle', '1', 'Diccionari');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '32', 'oc.pageTitle', '1', 'Diccionari');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '33', 'oc.pageBean', '1', 'typeMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '33', 'label', '1', 'General');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '33', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '34', 'label', '1', 'Propietats');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '34', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '34', 'oc.pageBean', '1', 'typePropertiesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '35', 'oc.pageBean', '1', 'typeACLBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '35', 'label', '1', 'Seguretat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '35', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '36', 'documentSearchMid', '1', '7');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '36', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '36', 'oc.pageBean', '1', 'documentRelatedBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '36', 'label', '1', 'Docs. relacionats');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'oc.objectBean', '1', 'personBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'oc.searchBean', '1', 'personSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'oc.objectTitle', '1', 'Persona');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'oc.searchTitle', '1', 'Cercador de persones');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'label', '1', 'Persones');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '37', 'action', '1', 'person_search');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '38', 'label', '1', 'Identificació');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '38', 'oc.pageBean', '1', 'personMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '38', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '39', 'action', '1', '#{caseSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '39', 'label', '1', 'Expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '39', 'oc.objectBean', '1', 'caseBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '39', 'oc.searchTitle', '1', 'Cercador d''expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '39', 'oc.objectTitle', '1', 'Expedient');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '40', 'oc.pageBean', '1', 'caseMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '40', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '40', 'label', '1', 'Descripció');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '41', 'oc.pageBean', '1', 'casePersonsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '41', 'label', '1', 'Persones');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '41', 'rendered', '1', '#{caseBean.personsTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '41', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '42', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '42', 'label', '1', 'Llocs');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '42', 'oc.pageBean', '1', 'caseAddressesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '42', 'rendered', '1', '#{caseBean.addressesTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '43', 'rendered', '1', '#{caseBean.documentsTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '43', 'oc.pageBean', '1', 'caseDocumentsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '43', 'label', '1', 'Documents');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '43', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '44', 'oc.pageBean', '1', 'caseACLBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '44', 'rendered', '1', '#{caseBean.ACLTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '44', 'label', '1', 'Seguretat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '44', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '45', 'rendered', '1', '#{caseBean.casesTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '45', 'oc.pageBean', '1', 'caseCasesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '45', 'caseSearchMid', '1', '30');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '45', 'label', '1', 'Expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '46', 'oc.pageBean', '1', 'casePoliciesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '46', 'label', '1', 'Polítiques');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '46', 'case_analizer', '1', 'case_analizer.xml');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '46', 'rendered', '1', '#{caseBean.dispositionsTabRendered and !caseBean.new}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'action', '1', '#{controllerBean.search}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'oc.objectTitle', '1', 'Domicili');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'oc.objectBean', '1', 'addressBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'oc.searchTitle', '1', 'Cercador de domicilis');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'oc.searchBean', '1', 'addressSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '47', 'label', '1', 'Domicilis');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'oc.pageTitle', '1', 'Cercador de països');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'oc.objectBean', '1', 'countryBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'action', '1', '#{countryToStreetBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'oc.searchBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'oc.pageBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '48', 'label', '1', 'País');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'action', '1', '#{countryToStreetBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'oc.objectBean', '1', 'provinceBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'oc.searchBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'oc.pageTitle', '1', 'Cercador de províncies');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'oc.pageBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '49', 'label', '1', 'Provincia');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'oc.searchBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'action', '1', '#{countryToStreetBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'oc.pageBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'oc.objectBean', '1', 'cityBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'oc.pageTitle', '1', 'Cercador de municipis');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '50', 'label', '1', 'Municipi');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'label', '1', 'Carrer');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'oc.pageTitle', '1', 'Cercador de carrers');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'oc.pageBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'oc.objectBean', '1', 'streetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'action', '1', '#{countryToStreetBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '51', 'oc.searchBean', '1', 'countryToStreetBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '52', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '52', 'label', '1', 'Adreces');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '52', 'oc.pageBean', '1', 'personAddressesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '53', 'oc.pageBean', '1', 'personContactsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '53', 'label', '1', 'Contactes');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '53', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '54', 'label', '1', 'Representants');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '54', 'oc.pageBean', '1', 'personRepresentantsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '54', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '55', 'label', '1', 'Expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '55', 'oc.pageBean', '1', 'personCasesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '55', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '56', 'oc.pageBean', '1', 'addressMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '56', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '56', 'label', '1', 'Descripció');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '57', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '57', 'label', '1', 'Persones');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '57', 'oc.pageBean', '1', 'addressPersonsBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '58', 'label', '1', 'Expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '58', 'oc.pageBean', '1', 'addressCasesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'oc.searchTitle', '1', 'Quadre de classificació');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'label', '1', 'QdC llista');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'oc.searchBean', '1', 'classSearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'action', '1', '#{classSearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'oc.objectBean', '1', 'classBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '59', 'classTreeMid', '1', '63');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '60', 'oc.objectTitle', '1', 'Sèrie');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '60', 'oc.pageBean', '1', 'classMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '60', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '60', 'label', '1', 'Metadades');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '61', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '61', 'oc.objectTitle', '1', 'Sèrie');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '61', 'oc.pageBean', '1', 'classHistoryBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '61', 'label', '1', 'Històric');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '62', 'label', '1', 'Polítiques');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '62', 'oc.pageBean', '1', 'classPoliciesBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '62', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '62', 'oc.objectTitle', '1', 'Sèrie');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '63', 'oc.searchTitle', '1', 'QdC');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '63', 'action', '1', '#{classTreeBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '63', 'oc.searchBean', '1', 'classTreeBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '63', 'label', '1', 'QdC arbre');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '64', 'render.expression', '1', '@_nodeid; ;@label');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '64', 'label', '1', 'Cataleg de tràmits');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '65', 'label', '1', 'Instància general');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '65', 'certificate', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '65', 'simular', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '65', 'signature', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '65', 'workflow', '1', 'general');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'frame', '1', 'default');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'catalogueIntro', '1', 'Escull el tràmit que vols començar:');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'label', '1', 'Tràmits on-line');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'action', '1', '#{procedureCatalogueBean.showCatalogue}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'instanceMid', '1', '67');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'template', '1', 'simple');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'catalogueMid', '1', '64');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '66', 'rightMenuMid', '1', 'disabled');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '67', 'label', '1', 'Els meus tràmits');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '67', 'showCatalogueMid', '1', '66');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '67', 'action', '1', '#{instanceListBean.main}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'url', '1', 'http://www.google.com');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'action', '1', 'url');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'template', '1', 'simple');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'roles.select', '1', 'WEBMASTER');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'rendered', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'label', '1', 'Tràmits');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '68', 'frame', '1', 'default');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'exitMid', '1', '69');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'catalogueIntro', '1', 'Escull el tràmit que vols començar:');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'instanceMid', '1', '70');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'label', '1', 'Tràmits on-line');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'catalogueMid', '1', '64');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '69', 'action', '1', '#{procedureCatalogueBean.showCatalogue}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'showCatalogueMid', '1', '69');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'action', '1', '#{instanceListBean.main}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'rendered', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'label', '1', 'Els meus tràmits');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '70', 'exitMid', '1', '70');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '71', 'workflow', '1', 'test_tramit');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '71', 'simular', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '71', 'label', '1', 'Tramit de test');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'action', '1', '#{documentBean.loadDocument}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'label', '1', 'Tramitacio');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'render.expression', '1', '@description;$; ;@_nodeid; ;@label');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'docId', '1', '5');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'frame', '1', 'default');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'instanceMid', '1', '76');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '72', 'template', '1', 'simple');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'label', '1', 'Tràmits on-line');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'instanceMid', '1', '76');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'catalogueIntro', '1', 'Escull el tràmit que vols començar:');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'catalogueMid', '1', '64');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '74', 'action', '1', '#{procedureCatalogueBean.showCatalogue}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '76', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '76', 'exitMid', '1', '72');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '76', 'label', '1', 'Els meus tràmits');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '76', 'action', '1', '#{instanceListBean.main}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '77', 'action', '1', '#{instanceListBean.main}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '77', 'roles.select', '1', 'EVERYONE');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '77', 'exitMid', '1', '77');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '77', 'rendered', '1', 'false');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '77', 'label', '1', 'Els meus tràmits 2');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '81', 'workflow', '1', 'test_certificat');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '81', 'label', '1', 'Tràmit de test de certificats');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '81', 'simular', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '81', 'certificate', '1', 'true');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'action', '1', '#{policySearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'oc.objectTitle', '1', 'Política');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'oc.searchBean', '1', 'policySearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'label', '1', 'Polítiques');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'oc.objectBean', '1', 'policyBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '82', 'oc.searchTitle', '1', 'Polítiques');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '83', 'action', '1', 'blank');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '83', 'oc.pageBean', '1', 'policyMainBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '83', 'label', '1', 'Principal');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '84', 'label', '1', 'Pol. sobre documents');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '84', 'oc.searchTitle', '1', 'Polítiques sobre documents');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '84', 'oc.searchBean', '1', 'documentPolicySearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '84', 'action', '1', '#{documentPolicySearchBean.show}');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '85', 'oc.searchTitle', '1', 'Polítiques sobre expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '85', 'oc.searchBean', '1', 'casePolicySearchBean');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '85', 'label', '1', 'Pol. sobre expedients');

INSERT INTO CMS_PROPERTY
(WORKSPACEID, NODEID, NAME, IDX, VALUE)
VALUES
('1', '85', 'action', '1', '#{casePolicySearchBean.show}');

UPDATE TABLESEQ SET VALUE = (SELECT MAX(NODEID) FROM CMS_NODE) WHERE counter = 'cms.node';

