ALTER TABLE LOG_PROPERTY DISABLE CONSTRAINT LOG_PROPERTY_ACCESS_FK;
ALTER TABLE LOG_ACCESS DISABLE CONSTRAINT LOG_ACCESS_FILE_FK;
TRUNCATE TABLE LOG_PROPERTY;
TRUNCATE TABLE LOG_ACCESS;
TRUNCATE TABLE LOG_FILE;
DROP SEQUENCE LOG_FILE_SEQUENCE;
CREATE SEQUENCE LOG_FILE_SEQUENCE INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCACHE NOCYCLE;
ALTER TABLE LOG_ACCESS ENABLE CONSTRAINT LOG_ACCESS_FILE_FK;
ALTER TABLE LOG_PROPERTY ENABLE CONSTRAINT LOG_PROPERTY_ACCESS_FK;
