package org.santfeliu.form.builder;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.matrix.dic.DictionaryManagerPort;
import org.matrix.dic.DictionaryManagerService;
import org.matrix.dic.EnumType;
import org.matrix.dic.Property;
import org.matrix.dic.PropertyDefinition;
import org.matrix.dic.PropertyType;
import org.matrix.util.WSEndpoint;
import org.santfeliu.dic.Type;
import org.matrix.doc.Document;
import org.matrix.doc.DocumentConstants;
import org.matrix.doc.DocumentFilter;
import org.matrix.doc.OrderByProperty;
import org.matrix.util.WSDirectory;
import org.santfeliu.dic.TypeCache;
import org.santfeliu.doc.client.DocumentManagerClient;
import org.santfeliu.form.Field;
import org.santfeliu.form.Form;
import org.santfeliu.form.FormDescriptor;
import org.santfeliu.form.View;
import org.santfeliu.form.type.html.HtmlField;
import org.santfeliu.form.type.html.HtmlForm;
import org.santfeliu.form.type.html.HtmlSelectView;
import org.santfeliu.form.type.html.HtmlView;

/**
 *
 * @author realor
 */
public class TypeFormBuilder extends MatrixFormBuilder
{
  public static final String PREFIX = "type";
  public static final String SEARCH_PREFIX = "searchtype";
  public static final String VIEW_PREFIX = "viewtype";
  public static final String USERID = "&userid=";
  public static final String PASSWORD = "&password=";
  public static final String TYPE_PROPERTY = "typeId";
  public static final String SEARCH_TYPE_PROPERTY = "searchTypeId";
  public static final String VIEW_TYPE_PROPERTY = "viewTypeId";
  public static final String AUTOMATIC_FORM_PROPERTY = "_automaticFormEnabled";
  public static final String AUTOMATIC_SEARCH_FORM_PROPERTY = "_automaticSearchFormEnabled";
  public static final String AUTOMATIC_VIEW_FORM_PROPERTY = "_automaticViewFormEnabled";
  public static final int LABEL_COLUMN_WIDTH = 19; // percertage

  public static enum FormMode
  {
    EDIT,
    SEARCH,
    VIEW
  }

  public List<FormDescriptor> findForms(String selector)
  {
    SelectorParser parser = new SelectorParser(selector);
    Type type = parser.getType();
    if (type != null)
    {
      try
      {
        DocumentManagerClient docClient = 
          getDocumentManagerClient(parser.getUserId(), parser.getPassword());

        List<FormDescriptor> descriptors = new ArrayList();
        addUserForms(type, parser.getFormMode(), descriptors, docClient);
        Collections.reverse(descriptors);

        addAutoForm(type, parser.getFormMode(), descriptors);

        return descriptors;
      }
      catch (Exception ex)
      {
      }
    }
    return Collections.EMPTY_LIST;
  }

  public Form getForm(String selector)
  {
    SelectorParser parser = new SelectorParser(selector);
    Type type = parser.getType();
    if (type != null)
    {
      return createForm(type, parser.getFormMode());
    }
    return null;
  }

  protected HtmlForm createForm(Type type, FormMode formMode)
  {
    HtmlForm form = new HtmlForm();
    form.setEncoding("UTF-8");
    form.setTitle("Autogenerated form: " + type.getDescription() +
     " (" + type.getTypeId() + ")");

    HtmlView bodyView = new HtmlView("body", View.GROUP);
    HtmlView tableView = new HtmlView("table", View.GROUP);
    tableView.setProperty("style", "width:100%;border-collapse:collapse");
    bodyView.getChildren().add(tableView);
    form.setRootView(bodyView);

    // add fields to form
    List<PropertyDefinition> pdList = 
      type.getPropertyDefinition(false, true, false);
    for (PropertyDefinition pd : pdList)
    {
      addFormField(form, formMode, tableView, pd);
    }
    return form;
  }

  protected void addFormField(HtmlForm form, FormMode formMode,
    HtmlView tableView, PropertyDefinition property)
  {
    if (!property.isHidden())
    {
      // create field
      HtmlField field = new HtmlField();
      field.setReference(property.getName());
      field.setLabel(property.getDescription());
      field.setMinOccurs(formMode.equals(FormMode.SEARCH) ? 0 : property.getMinOccurs());
      field.setMaxOccurs(property.getMaxOccurs());
      if (!formMode.equals(FormMode.SEARCH))
        field.setReadOnly(property.isReadOnly());
      form.addField(field);

      // create view
      HtmlView rowView = new HtmlView("tr", View.GROUP);
      tableView.getChildren().add(rowView);

      HtmlView col1View = new HtmlView("td", View.GROUP);
      rowView.getChildren().add(col1View);
      HtmlView labelView = new HtmlView("#text", View.LABEL);
      col1View.getChildren().add(labelView);
      col1View.setProperty("style", "width:" + LABEL_COLUMN_WIDTH + "%");
      String label = field.getLabel();
      if (!label.endsWith(":")) label += ":";
      labelView.setProperty("text", label);

      HtmlView col2View = new HtmlView("td", View.GROUP);
      rowView.getChildren().add(col2View);
      int valueColumnWidth = 100 - LABEL_COLUMN_WIDTH;
      col2View.setProperty("style", "width:" + valueColumnWidth + "%");

      HtmlView inputView = null;

      String enumTypeId = property.getEnumTypeId();
      if (enumTypeId != null) // enum type property
      {
        EnumType enumType = getEnumType(enumTypeId);
        switch (enumType.getItemType())
        {
          case TEXT: field.setType(Field.TEXT); break;
          case NUMERIC: field.setType(Field.NUMBER); break;
          case BOOLEAN: field.setType(Field.BOOLEAN); break;
          case DATE: field.setType(Field.DATE); break;
        }
        inputView = new HtmlSelectView();
        inputView.setNativeViewType("select");
        inputView.setProperty("dataref", "enumtype:" + enumTypeId);
        if (property.getMaxOccurs() != 1) // multi-valued field
        {
          inputView.setProperty("multiple", "true");
          inputView.setProperty("renderer", "checkBoxList");
          inputView.setProperty("size", "4");
          inputView.setProperty("class", field.isReadOnly() ? 
            "readOnlySelectBox" : "selectBox inline");
        }
        else // single-value field
        {
          inputView.setProperty("class", field.isReadOnly() ? 
            "readOnlySelectBox" : "selectBox");
          if (formMode.equals(FormMode.SEARCH) || property.getMinOccurs() == 0) // single-value
          {
            // add empty value (NULL)
            HtmlView option = createSelectOption("", "");
            inputView.getChildren().add(option);
          }
        }
      }
      else if (property.getType() == PropertyType.TEXT)
      {
        field.setType(Field.TEXT);
        inputView = new HtmlView("input", View.TEXTFIELD);
        inputView.setProperty("type", "text");
        int size = property.getSize();
        if (size > 0)
        {
          inputView.setProperty("size", String.valueOf(Math.min(size, 70)));
          inputView.setProperty("maxlength", String.valueOf(size));
        }
        else
        {
          inputView.setProperty("size", "70");
        }
        inputView.setProperty("class", "inputBox");
        if (!property.getValue().isEmpty())
        {
          inputView.setProperty("value", property.getValue().get(0));
        }
      }
      else if (property.getType() == PropertyType.NUMERIC)
      {
        field.setType(Field.NUMBER);
        inputView = new HtmlView("input", View.TEXTFIELD);
        inputView.setProperty("type", "text");
        inputView.setProperty("style", "width:100px");
        inputView.setProperty("class", "inputBox");
        if (!property.getValue().isEmpty())
        {
          inputView.setProperty("value", property.getValue().get(0));
        }
      }
      else if (property.getType() == PropertyType.BOOLEAN)
      {
        field.setType(Field.BOOLEAN);
        if (field.getMinOccurs() == 0 || formMode.equals(FormMode.SEARCH)) // draw select [NULL/T/F]
        {
          inputView = new HtmlView("select", View.SELECT);
          inputView.setProperty("class", "selectBox");
          HtmlView option1 = createSelectOption("", "");
          HtmlView option2 = createSelectOption("true", "TRUE");
          HtmlView option3 = createSelectOption("false", "FALSE");
          inputView.getChildren().add(option1);
          inputView.getChildren().add(option2);
          inputView.getChildren().add(option3);
          if (!property.getValue().isEmpty())
          {
            String value = property.getValue().get(0);
            if ("true".equals(value))
            {
              option2.setProperty("selected", "selected");
            }
            else if ("false".equals(value))
            {
              option3.setProperty("selected", "selected");
            }
          }
        }
        else // field is not nullable, paint as checkbox
        {
          inputView = new HtmlView("input", View.TEXTFIELD);
          inputView.setProperty("type", "checkbox");
          if (!property.getValue().isEmpty())
          {
            if ("true".equals(property.getValue().get(0)))
            {
              inputView.setProperty("checked", "true");
            }
          }
        }
      }
      else if (property.getType() == PropertyType.DATE)
      {
        field.setType(Field.DATE);
        inputView = new HtmlView("input", View.TEXTFIELD);
        inputView.setProperty("type", "text");
        inputView.setProperty("format", "date");
        inputView.setProperty("style", "width:100px");
        inputView.setProperty("class", "inputBox");
        if (!property.getValue().isEmpty())
        {
          inputView.setProperty("value", property.getValue().get(0));
        }
      }
      if (inputView != null)
      {
        inputView.setProperty("name", field.getReference());
        inputView.setReference(field.getReference());
        if (field.isReadOnly()) inputView.setProperty("disabled", "true");
        col2View.getChildren().add(inputView);
        form.linkView(inputView, field);
      }
    }
  }

  protected void addUserForms(Type type, FormMode formMode,
    List<FormDescriptor> descriptors, DocumentManagerClient docClient)
    throws Exception
  {
    if (type != null)
    {
      DocumentFilter filter = new DocumentFilter();
      filter.setVersion(0);
      filter.setDocTypeId(FORM_TYPEID);
      Property property = new Property();
      if (FormMode.SEARCH.equals(formMode))
        property.setName(SEARCH_TYPE_PROPERTY);
      else if (FormMode.VIEW.equals(formMode))
        property.setName(VIEW_TYPE_PROPERTY);
      else
        property.setName(TYPE_PROPERTY);
      property.getValue().add(type.getTypeId());
      filter.getProperty().add(property);

      OrderByProperty orderBy = new OrderByProperty();
      orderBy.setName(DocumentConstants.TITLE);
      orderBy.setDescending(true);
      filter.getOrderByProperty().add(orderBy);
      List<Document> documents = docClient.findDocuments(filter);

      for (Document document : documents)
      {
        FormDescriptor descriptor = new FormDescriptor();
        String title = document.getTitle();
        int index = title.indexOf(":"); // remove form name.
        if (index != -1)
        {
          title = title.substring(index + 1);          
        }
        if (title.length() == 0) title = type.getTypeId();
        descriptor.setTitle(title);
        descriptor.setSelector(
          DocumentFormBuilder.PREFIX + ":" + document.getDocId());
        descriptors.add(descriptor);
      }
      addUserForms(type.getSuperType(), formMode, descriptors, docClient);
    }
  }

  protected void addAutoForm(Type type, FormMode formMode,
    List<FormDescriptor> descriptors)
  {
    boolean automaticEnabled = true;
    String propertyName = AUTOMATIC_FORM_PROPERTY;
    if (FormMode.SEARCH.equals(formMode))
      propertyName = AUTOMATIC_SEARCH_FORM_PROPERTY;
    else if (FormMode.VIEW.equals(formMode))
      propertyName = AUTOMATIC_VIEW_FORM_PROPERTY;

    PropertyDefinition automaticProperty =
      type.getPropertyDefinition(propertyName);
    if (automaticProperty != null)
    {
      if (!automaticProperty.getValue().isEmpty())
      {
        String value = automaticProperty.getValue().get(0);
        automaticEnabled = "true".equalsIgnoreCase(value) 
          || ("auto".equalsIgnoreCase(value) && descriptors.isEmpty());
      }
    }
    if (automaticEnabled)
    {
      if (!type.getPropertyDefinition(false, true, false).isEmpty())
      {
        FormDescriptor descriptor = new FormDescriptor();
        descriptor.setTitle("Automatic form for " + type.getTypeId());
        String prefix = FormMode.SEARCH.equals(formMode) ? SEARCH_PREFIX :
          FormMode.VIEW.equals(formMode) ? VIEW_PREFIX : PREFIX;
        descriptor.setSelector(prefix + ":" + type.getTypeId());
        descriptors.add(descriptor);
      }
    }
  }

  protected EnumType getEnumType(String enumTypeId)
  {
    EnumType enumType = null;
    try
    {
      WSDirectory wsDir = WSDirectory.getInstance();
      WSEndpoint endpoint = wsDir.getEndpoint(DictionaryManagerService.class);
      DictionaryManagerPort port = endpoint.getPort(DictionaryManagerPort.class);
      return port.loadEnumType(enumTypeId);
    }
    catch (Exception ex)
    {
    }
    return enumType;
  }

  private HtmlView createSelectOption(String value, String label)
  {
    HtmlView option = new HtmlView();
    option.setNativeViewType("option");
    option.setViewType(View.ITEM);
    option.setProperty("value", value);
    HtmlView optionValue = new HtmlView();
    optionValue.setNativeViewType("#text");
    optionValue.setViewType(View.LABEL);
    optionValue.setProperty("text", label);
    option.getChildren().add(optionValue);
    return option;
  }

  class SelectorParser
  {
    private String typeId;
    private String userId;
    private String password;
    private FormMode formMode;

    SelectorParser(String selector)
    {
      String prefix = selector.startsWith(PREFIX + ":") ? PREFIX : 
        (selector.startsWith(SEARCH_PREFIX + ":") ? SEARCH_PREFIX : 
        (selector.startsWith(VIEW_PREFIX + ":") ? VIEW_PREFIX : null));
      if (prefix != null)
      {
        formMode = prefix.equals(SEARCH_PREFIX) ? FormMode.SEARCH :
          prefix.equals(VIEW_PREFIX) ? FormMode.VIEW : FormMode.EDIT;
        typeId = extract(selector.substring(prefix.length() + 1), null, USERID);
        userId = extract(selector, USERID, PASSWORD);
        password = extract(selector, PASSWORD, null);
      }
    }

    public String getTypeId()
    {
      return typeId;
    }

    public Type getType()
    {
      if (typeId == null) return null;
      TypeCache typeCache = TypeCache.getInstance();
      return typeCache.getType(typeId);
    }

    public String getUserId()
    {
      return userId;
    }

    public String getPassword()
    {
      return password;
    }

    public FormMode getFormMode()
    {
      return formMode;
    }

    private String extract(String selector, String startToken, String endToken)
    {
      String value = null;
      int index;
      if (startToken == null)
      {
        index = 0;
        value = selector;
      }
      else
      {
        index = selector.indexOf(startToken);
        if (index != -1)
        {
          value = selector.substring(index + startToken.length());
        }
      }
      if (value != null)
      {
        if (endToken != null)
        {
          int index2 = value.indexOf(endToken);
          if (index2 != -1)
          {
            value = value.substring(0, index2);
          }
        }
      }
      return value;
    }
  }
}
